### ISSUE TITLE
Crosshatch pattern in cube render

### ISSUE THREAD

**Issue by drtobybrown** [CARTAvis/carta#10]
I'm having issues with how datacubes look when rendered in CARTA Remote version 1.2.2 on Firefox 72.0.1 (64-bit). 

You can see from the screenshots, there is artificial crosshatch pattern of approximately 4x4 pixels imprinted on the cube when displayed in CARTA. This pattern does not appear when the same cube file and channel is displayed in the CASA Viewer.

<img width="2648" alt="carta-cube" src="https://user-images.githubusercontent.com/6336385/73765267-4d637a00-4742-11ea-8541-5483369a2253.png">
<img width="2552" alt="casa-viewer-cube" src="https://user-images.githubusercontent.com/6336385/73765190-315fd880-4742-11ea-90af-d4d74ad7761f.png">

The same pattern is clearly visible in the PSF cube in CARTA but again not in the CASA Viewer.
<img width="2648" alt="carta-psf" src="https://user-images.githubusercontent.com/6336385/73765528-a92e0300-4742-11ea-95b5-6abfdf902662.png">
<img width="2552" alt="casa-viewer-psf" src="https://user-images.githubusercontent.com/6336385/73765527-a92e0300-4742-11ea-980f-e647b3fc84f2.png">

**Comment by kswang1029** [comment]
how did you make the image? with tclean in parallel mode?

**Comment by drtobybrown** [comment]
No, I don't think so.

               tclean(vis=self.vis,
               imagename=self.image_root,
               phasecenter=self.phase_center,
               cell=self.cell_size,
               imsize=self.image_size,
               gridder='mosaic',
               # Selection
               #antenna=self.antenna,
               # Spectral axis
               specmode=self.specmode,
               restfreq=restfreq_str,
               outframe='lsrk',
               veltype='radio',
               # Workflow
               calcres=self.calcres,
               calcpsf=self.calcpsf,
               # Deconvolver
               deconvolver=self.deconvolver,
               scales=self.scales_as_pix,
               smallscalebias=self.smallscalebias,
               pblimit=self.pblimit,
               normtype='flatnoise',
               # Restoring beam
               restoringbeam=self.restoringbeam,
               # U-V plane gridding
               weighting='briggs',
               robust=self.briggs_weight,
               uvtaper=uv_taper_string,
               # Stopping criterion
               niter=self.niter,
               threshold=self.threshold,
               cycleniter=self.cycle_niter,
               cyclefactor=3.0,
               minpsffraction=self.minpsffraction,
               # Mask
               usemask=self.usemask,
               mask=self.mask,
               pbmask=self.pblimit,
               # UI
               interactive=self.interactive,
               )

**Comment by kswang1029** [comment]
could you share the psf cube (few channels) with us for further diagnostics?

**Comment by veggiesaurus** [comment]
This might be a compression artefact. Can you see what happens if you increase the compression setting in your preferences dialog (under the performance tab)

**Comment by drtobybrown** [comment]
> This might be a compression artefact. Can you see what happens if you increase the compression setting in your preferences dialog (under the performance tab)

This was it. Bumping the compression number (factor?) from 4 to 10 fixed the issue. A compression number of 6 did ok but still not ideal.

The psf can [be found here.](https://www.dropbox.com/s/6i6ne7nz2pv3s8x/testchans.psf.fits?dl=0)

If it's not already, this is something that might be worth mentioning somewhere. In particular, when you decrease the pixel size in tclean there's risk that this compression artifact pops up.

**Comment by veggiesaurus** [comment]
> > This might be a compression artefact. Can you see what happens if you increase the compression setting in your preferences dialog (under the performance tab)
> 
> This was it. Bumping the compression number (factor?) from 4 to 10 fixed the issue. A compression number of 6 did ok but still not ideal.
> 
> The psf can [be found here.](https://www.dropbox.com/s/6i6ne7nz2pv3s8x/testchans.psf.fits?dl=0)
> 
> If it's not already, this is something that might be worth mentioning somewhere. In particular, when you decrease the pixel size in tclean there's risk that this compression artifact pops up.

The default compression level is 11, I think. I agree it should be carefully documented. Generally we suggest staying above 7. Although this needs to be documented in more detail

**Comment by kswang1029** [comment]
@veggiesaurus shall we put something in the appendix of the user manual?

Alternatively is it possible to just limit the parameter from 7 to prevent this kind of issue, if we are sure <7 will never be useful?

**Comment by veggiesaurus** [comment]
> @veggiesaurus shall we put something in the appendix of the user manual?
> 
> Alternatively is it possible to just limit the parameter from 7 to prevent this kind of issue, if we are sure <7 will never be useful?

Both good ideas 👍
