### ISSUE TITLE
Link to the docs from the homepage

### ISSUE THREAD

**Issue by keflavich** [CARTAvis/carta#103]
https://cartavis.org/ doesn't seem to link to https://carta.readthedocs.io/en/latest/ at the top level; the links are hidden in installation instructions (https://carta.readthedocs.io/en/2.0/installation_and_configuration.html).  There should be a link probably at the top level along the navigation bar.

I'm asking partly because "carta" always googles/autocompletes to cartavis, but then I have to hunt for the link to what I really want (docs!)

**Comment by kswang1029** [comment]
@keflavich thanks for the suggestion. Please check https://cartavis.org/ again (or in few mins to update). There is a new button added which points to the user manual directly as a new webpage.

**Comment by keflavich** [comment]
lgtm!
![image](https://user-images.githubusercontent.com/143715/142710771-0b8facc2-d2b6-4baf-b831-17d48c48a20d.png)
