### ISSUE TITLE
Feature request: per-image titles in multipanel view

### ISSUE THREAD

**Issue by keflavich** [CARTAvis/carta#104]
Multi-panel view is great!  It would be helpful to have per-image titles:

![image](https://user-images.githubusercontent.com/143715/142710941-8120764f-6a5b-44b5-ab89-f609fbee5b42.png)

If this is documented, I couldn't find it.   I searched for "[multi](https://carta.readthedocs.io/en/latest/search.html?q=multi)", "multi-panel", "[multipanel](https://carta.readthedocs.io/en/latest/search.html?q=multipanel)", and "title" on https://carta.readthedocs.io/en/latest/search.html

**Comment by kswang1029** [comment]
Multiple panel view is a post v2 feature as a v3beta feature. At the moment we do not have user manual for betas.

**Comment by keflavich** [comment]
fair enough.  Consider this a future documentation request then

**Comment by kswang1029** [comment]
(as of v3b2) per panel title can be set via the settings dialog of the image viewer. ![S255_CH3CN_subcube.fits-M17_SWex.hdf5-image-2022-03-17-11-40-49.png](https://images.zenhubusercontent.com/590bdf9f51aa2c30577d5260/31428a07-6e41-4ed5-aa75-1938332677a9)
