### ISSUE TITLE
Feature Request: Spatially Linking PV Diagrams

### ISSUE THREAD

**Issue by CarlosECarrilloGallegos** [CARTAvis/carta#107]
I am loading in two PV diagrams. The two PV diagrams are made from two separate FITS Cubes with different velocity channels and steps, but are cut over the same WCS region. I am trying to spatially match the PV diagrams in CARTA to overlay one diagram over the other. Every time I attempt to, this message is returned:

“
Could not enable spatial matching of “PV_diagram_1.fits” to reference image “PV_diagram_2.fits.” No valid transform was found.
“

I attempted the same with two PV diagrams from the same FITS Cube, and the same issue was returned. 

The ability to match PV diagrams spatially would be very useful if its not already implemented (in which case, I am not entirely sure how it works).

**Comment by kswang1029** [comment]
@CarlosECarrilloGallegos matching PV images is not possible in CARTA. We will need to think about this a bit more on feasibility.
