### ISSUE TITLE
unable to export regions on https://carta.idia.ac.za/

### ISSUE THREAD

**Issue by pjmac1105** [CARTAvis/carta#109]
Hi team, when I try and export the regions on my image, after clicking "Export Regions" it displays the error "Export region failed: cannot create file". 

I am logged in to https://carta.idia.ac.za/, it was doing this last week as well - I have logged out and back in but the issue is still there. I have also tried all combinations of CRTF/DS9 with World/Pixel.

Regards,
Peter Macgregor.

![image](https://user-images.githubusercontent.com/19280051/144771884-939a2f56-7251-4905-9fa6-c306a6b2535c.png)

**Comment by veggiesaurus** [comment]
Do you have write permissions on the folder that you're trying to create the region file in? I suspect this is an issue specific to IDIA, rather than a CARTA issue.

**Comment by Jordatious** [comment]
Hey @pjmac1105! On this CARTA server, the `/idia` mount is read-only, so you cannot export region files, FITS cutouts or moment maps here, but it is possible to do write them to `/scratch3` or `/carta_share`, so please try writing it there. Please let me know if you have any further issues.
