### ISSUE TITLE
CARTA doesnt play well with OneDrive/Dropbox on Mac

### ISSUE THREAD

**Issue by TimothyADavis** [CARTAvis/carta#112]
Dear CARTA team,

Thanks for creating this great program! I am, however, encountering an issue that is stopping me from adopting it at this time. 

I keep many of my fits files on Dropbox and OneDrive, both of which have a mode (on a mac at least) where you can store files online-only, and only download them locally when they are needed. 

If I try and open a file in CARTA that's been stored in this manner, as soon as I open the folder in the CARTA internal file browser it starts downloading every single fits file in that folder, even before I have clicked on any of them! This obviously isn't ideal behavior... I don't know why this happens- perhaps CARTA is already trying to do something to the files even before they are selected?

Many thanks,
Tim Davis

**Comment by kswang1029** [comment]
Hi @TimothyADavis by default CARTA reads metadata of all files in a folder to determine the image formats (CASA, FITS, MIRIAD or HDF5). I think this is why you see all files are being downloaded to local. 

If you use v3b2 version, could you try to change this behavior in the preference to see if the situation is improved?
<img width="766" alt="Screen Shot 2022-01-17 at 19 52 11" src="https://user-images.githubusercontent.com/20819712/149765252-97172679-5057-4446-ba2f-7048acba9d5d.png">

**Comment by veggiesaurus** [comment]
Hi Tim

I suspect what's happening is that we use the [file signature](https://en.wikipedia.org/wiki/List_of_file_signatures) to determine the file type. This means we need to read the first 8 bytes of file. I think this is what's going on. 

We introduced additional options for filtering by file extension in the latest 3.0 beta, which you can find [here](https://github.com/CARTAvis/carta/releases/tag/v3.0.0-beta.2b). Once installed, go to `Preferences -> Global -> File list` to filter by extension, or simply show all files (a la DS9). Hopefully that solves the issue!

**Comment by TimothyADavis** [comment]
That seems to work perfectly! Many thanks.
