### ISSUE TITLE
overly restrictive permissions (rwx------) on some files inside the installation tarball

### ISSUE THREAD

**Issue by o-smirnov** [CARTAvis/carta#12]
I'm getting an odd problem deploying CARTA 1.2.2 remote inside a Singularity container.

Everything works fine with versions up to and including 1.2.1. But when I deploy 1.2.2 in an otherwise identical image, it refuses to serve up CARTA components. 

I'm running the remote as:
```
carta --remote --root=/home/oms/projects/radiopadre-tutorial --folder=/home/oms/projects/radiopadre-tutorial --port=1043 --fport=1042
```

I then get a blank webpage titled "CARTA" when connecting to ``http://localhost:1042/?socketUrl=ws://localhost:1043``

If I look at the HTML source in the browser, I see that the normal CARTA startup HTML is served up, so it's at least partially working:

```html
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no"><meta name="theme-color" content="#000000"><link rel="manifest" href="./manifest.json"><link rel="shortcut icon" href="./carta_icon_128px.png"><title>CARTA</title><link href="./static/css/main.9d133f1a.css" rel="stylesheet"></head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div><script type="text/javascript" src="./static/js/main.8d8fc265.js"></script></body></html>
```

...but it returns a 404 when the CSS and Javascript components are requested (as e.g. ``http://localhost:1042/static/css/main.9d133f1a.css``):

```html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
        "http://www.w3.org/TR/html4/strict.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=utf-8">
        <title>Error response</title>
    </head>
    <body>
        <h1>Error response</h1>
        <p>Error code: 404</p>
        <p>Message: File not found.</p>
        <p>Error code explanation: HTTPStatus.NOT_FOUND - Nothing matches the given URI.</p>
    </body>
</html>
```
I stress that 1.2.1 works perfectly fine in the same scenario, so it must be a recent change.

(To muddy the waters further -- 1.2.2 works fine under Docker...)

**Comment by o-smirnov** [comment]
Hmmm, I'm not sure if anyone is reading this, but for the record: the problem is permissions inside the 1.2.2 (and 1.3) distribution tarball.

Both ``carta_remote`` and ``static/`` are ``rwx------``. I don't know if this was intentional, but I can't see any reason to *not* have these world-readable.

(Singularity is running the remote with a different UID from the installer's UID somehow, which prevents pages from static being served up.)

Doing a chmod after unpacking the tarball solves the problem.

**Comment by veggiesaurus** [comment]
Thanks for finding this. @ajm-asiaa is this something you can easily fix?

**Comment by ajm-ska** [comment]
I'm sorry about the slow response. Thank you for finding the problem and solution @o-smirnov. I'm not sure how or why all the directories ended up with `drwx------` permissions. The `carta-backend` directory and all directories inside it were the same. I have now given all the v1.2.2 and v1.3 remote version directories 744 permissions (`drwxr--r--`) and re-uploaded their tarballs to Github.
