### ISSUE TITLE
Drawing region disconnects from server v1.3

### ISSUE THREAD

**Issue by drtobybrown** [CARTAvis/carta#13]
The .fits file loads perfectly.
![Screenshot 2020-04-01 at 18 41 50](https://user-images.githubusercontent.com/6336385/78193471-a0a72f80-7448-11ea-9791-42ba9f34e866.png)

However, when click the region button I get disconnected from the server (top right) every time. I'm not even sure what server means in this case as I'm running the standard v1.3 install on my local machine (MacOS 10.15).
![Screenshot 2020-04-01 at 18 41 57](https://user-images.githubusercontent.com/6336385/78193587-da783600-7448-11ea-9bb9-505b3787fce3.png)

Cheers
Toby

**Comment by kswang1029** [comment]
Could you provide this image for further diagnostics?

**Comment by drtobybrown** [comment]
It's proprietary but would be happy to share via private communication - send me an email at brownt16@mcmaster.ca

**Comment by kswang1029** [comment]
fixed in v1.3.1.
