### ISSUE TITLE
Fits file stops CARTA responding

### ISSUE THREAD

**Issue by drtobybrown** [CARTAvis/carta#14]
CARTA v1.3 is struggling to parse relevant info such as pixel values and basic stats from a .fits (ds9 loads it fine). 

![Screenshot 2020-04-01 at 18 49 27](https://user-images.githubusercontent.com/6336385/78194398-0dbbc480-744b-11ea-9af2-049b9db3ee86.png)

It also stops CARTA responding when I load in another .fits that I know works when opened on its own. - see video 

[Screen Recording 2020-04-01 at 18.53.52.mov.zip](https://github.com/CARTAvis/carta/files/4418022/Screen.Recording.2020-04-01.at.18.53.52.mov.zip)

It would also be useful in  tracking down this issue if the log could print helpful error messages

I've attached the fits file in question which is public anyway.

**Comment by kswang1029** [comment]
from the video, it appears image data of the newly loaded image were streaming but got stuck. would it be possible to provide those test images for further diagnostics? A sub image should be sufficient if those are proprietary data.

**Comment by drtobybrown** [comment]
Happy to share the files - they're public so no issues.

[Archive.zip](https://github.com/CARTAvis/carta/files/4422376/Archive.zip)

**Comment by kswang1029** [comment]
fixed in v1.3.1
