### ISSUE TITLE
Session always resumes in home directory in file browser

### ISSUE THREAD

**Issue by lh-astro** [CARTAvis/carta#144]
**Describe the bug**
When using the file browser and going into a different directory than the home directory CARTA does not memorise that directory after starting a new CARTA session.

**To Reproduce**
1. Open file browser and go into a different directory.
2. Close and re-open CARTA
3. Open the file browser.

**Expected behavior**
I expect to see that last opened directory in  the file browser, even after starting a new session.

**Screenshots or videos**

**Platform info (please complete the following information):**
- IDIA CARTA version 2 and 3.0

**Comment by kswang1029** [comment]
@lh-astro is this still an issue with v4-stable on ilifu?

**Comment by lh-astro** [comment]
@kswang1029 seem to be fixed with v4-stable on ilifu. Thank you!
