### ISSUE TITLE
Where are snippets stored?

### ISSUE THREAD

**Issue by keflavich** [CARTAvis/carta#151]
Where are the saved snippets stored?

I'd like to be able to:
- back them up [e.g., store them in a github repository]
- bulk create new ones
- edit existing snippets with other editors

**Comment by kswang1029** [comment]
`~/.carta/config/snippets` as `json` format

**Comment by keflavich** [comment]
strange, I see:
```
$ ls -a  ~/.carta/config/
.  ..  layouts  preferences.json
```
but I have several saved snippets.  Could there be another location?

**Comment by kswang1029** [comment]
Could you also check .carta-beta folder? 🤔️

**Comment by keflavich** [comment]
Ah that's it!  I have never used the release versions, only the beta version =).  Thanks!
