### ISSUE TITLE
Licence + code source

### ISSUE THREAD

**Issue by alaingdl** [CARTAvis/carta#156]
One colleague asked me to install this code but I was not able to found the license (GPL ? BSD ?) and, more strange, no source code around. Thanks for details

Alain C.

**Comment by kswang1029** [comment]
Please follow the installation part of https://cartavis.org/

usually you don’t need to build from the source code. Also depending on the use cases (individual users vs institutional-wide with multiple users) we have different modes of CARTA deployment.

**Comment by veggiesaurus** [comment]
@alaingdl you can find the source code for the various components ([front-end](https://github.com/CARTAvis/carta-frontend), [backend](https://github.com/CARTAvis/carta-backend) and [controller](https://github.com/CARTAvis/carta-controller)) in the other repos of this GitHub organisation.
