### ISSUE TITLE
Layout file

### ISSUE THREAD

**Issue by mphanderson** [CARTAvis/carta#159]
In the macOS version, is there a file where the layouts are stored? Is it possible to copy this file/its contents and sent it to other users?

For teaching purposes it would be amazing to be able to distribute a set of customised layouts across a whole set of computers in a lab/organisation.

**Comment by kswang1029** [comment]
@mphanderson the layout files are stored in ~/.carta/config/layouts in JSON format. You may copy the layout files to others and keep them at their <user_home>/.carta/config/layouts.

**Comment by mphanderson** [comment]
Thank you for your response @kswang1029. I've had a look in that `~/.carta` directory (both for the 2.0.0 and beta 3.x release), and there is only a `log/` subdirectory within. I do indeed have a custom layout saved (see attached)


<img width="653" alt="Screenshot 2022-08-11 at 10 06 24" src="https://user-images.githubusercontent.com/23109771/184100823-51d46310-0350-4301-bc5f-73856fdf18f5.png">

**Comment by veggiesaurus** [comment]
> Thank you for your response @kswang1029. I've had a look in that `~/.carta` directory (both for the 2.0.0 and beta 3.x release), and there is only a `log/` subdirectory within. I do indeed have a custom layout saved (see attached)
> 
> <img alt="Screenshot 2022-08-11 at 10 06 24" width="653" src="https://user-images.githubusercontent.com/23109771/184100823-51d46310-0350-4301-bc5f-73856fdf18f5.png">

@kswang1029 I think this is related to the issue @ajm-asiaa brought up. We only made the switch from localStorage post-2.0, and @ajm-asiaa built beta-3 without this change, IIRC.

**Comment by kswang1029** [comment]
Correct. The upcoming v3-stable release should work.

**Comment by mphanderson** [comment]
Great, thank you both!
