### ISSUE TITLE
carta_icon_128px.png missing from CARTA-v1.3-remote tarball

### ISSUE THREAD

**Issue by o-smirnov** [CARTAvis/carta#16]
Just a cosmetic -- but it's nice to have that icon at the top of the browser tab.

**Comment by veggiesaurus** [comment]
Well spotted! @ajm-asiaa is it a build issue?

**Comment by ajm-ska** [comment]
Thank you for spotting that @o-smirnov. I must have forgotten to copy it in. I see it was missing from v1.2.2 too. I have added it to both versions now and re-uploaded their tarballs to Github.
