### ISSUE TITLE
Please provide unzipped AppImage for download

### ISSUE THREAD

**Issue by probonopd** [CARTAvis/carta#163]
Please provide unzipped AppImage for download, like this:
https://github.com/CARTAvis/carta/releases/download/v3.0.0/CARTA-3.0.0-x86_64.AppImage

The reasons are explained at
https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages/cc2441518975caca23e9ce2dba6f08a22c678d1e#common-mistake

This way we can run the automated test for inclusion in appimage.github.io Thanks for providing an AppImage!

**Comment by ajm-ska** [comment]
Thanks to @probonopd 
CARTA is now on appimage.github.io: https://appimage.github.io/CARTA/
