### ISSUE TITLE
Migrate RPM hosting to Copr

### ISSUE THREAD

**Issue by ajm-ska** [CARTAvis/carta#167]
Currently, we host our CARTA RPMs on a server at ASIAA (https://packages.cartavis.org/). We can not guarantee that it will be available 24 hours a day, 365 days a year. It is also time-consuming to manually build, sign, and test each RPM (full release and beta release) on what has now become 6 supported RPM platforms: 

1. Red Hat 7 x86_64 
2. Red Hat 7 aarch64
3. Red Hat 8 x86_64
4. Red Hat 8 aarch64
5. Red Hat 9 x86_64
6. Red Hat 9 aarch64 

An alternative is to use [Fedora Copr](https://copr.fedorainfracloud.org/). Copr (Cool Other Package Repo) is a convenient free service to build and host third-party RPM package repositories, similar to [Ubuntu's Launchpad PPAs](https://launchpad.net/ubuntu/+ppas). It should save a lot of time. Although it is provided by Fedora, we can build packages only for EPEL7, EPEL8, and EPEL9 ('EPEL' stands for Extra Packages for Enterprise Linux)

Caveat: Copr does not provide el7 aarch64

Tasks:

* [x] Create a [Copr repository for CARTA](https://copr.fedorainfracloud.org/coprs/cartavis/carta/).

* [x] Modify our RPM SPEC files for the CARTA v3.0.0 release so that they can build on the Copr cloud servers (including additional packages required to build and run the Unit Tests e.g. newer gtest for el7 and el8).
  * [x] el7 x86_64
  * [x] el8 x86_64
  * [x] el8 aarch64
  * [x] el9 x86_64
  * [x] el9 aarch64

* [x] Modify all carta-backend RPM Dockerfiles to use the cartavis/carta Copr repository.

* [x]  Modify all CARTA documentation with instructions to use the cartavis/carta Copr repository instead of packages.cartavis.org.

* [x] Provide beta packages for the next CARTA-beta release, v4 beta-1.

* [x] Retire the old packages.cartavis.org server.

**Comment by veggiesaurus** [comment]
@ajm-asiaa can we close this?

**Comment by ajm-ska** [comment]
@veggiesaurus Not yet. I believe there are just two different documents left that need modifying:
1. [The CARTA Installation and Configuration page on the user manual.](https://carta.readthedocs.io/en/latest/installation_and_configuration.html#user-deployment-mode)
2. [The step by step instructions for CentOS8 on the carta-controller documentation.](https://carta-controller.readthedocs.io/en/latest/centos8_instructions.html)

I was actually trying to do it yesterday, but I got sidetracked by other things yesterday and today. I will try to do it tomorrow. I am sorry for the inconvenience.

**Comment by ajm-ska** [comment]
@veggiesaurus I think we can finally close this issue as completed now!
