### ISSUE TITLE
feature request: add support of contrast adjustment for raster image

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta#17]
This is a feature request sent via the carta_helpdesk email.

> Hi, 
I am using CARTA with the MeerKAT telescope on the idia cluster. I was wondering if there was some sort of tool to adjust the contrast in an image. I am most familiar with using ds9 and I often would use the middle mouse button to adjust the contrast. Is there an equivalent?
Thank you,
Sarah Chastain

**Comment by veggiesaurus** [comment]
removed estimate due to duplicate
