### ISSUE TITLE
Ellipses rotate 90 degrees upon export/import for WCS format

### ISSUE THREAD

**Issue by Jordatious** [CARTAvis/carta#18]
When I export an ellipse region using the IDIA server version of CARTA, using the default options of CTRF format, and world coordinates, and then import it again, it's rotated by 90 degrees, even when imported onto the same image. The same occurs when using ds9 region format, but doesn't seem to occur for either format when using pixel coordinates. None of the other region shapes seem to have this issue, at least for CTRF format and world coordinates.

**Comment by kswang1029** [comment]
fixed in v1.3.1
