### ISSUE TITLE
Feature request: option to disable header scans (?) in file browser

### ISSUE THREAD

**Issue by IanHeywood** [CARTAvis/carta#197]
I've got folders with many thousands of FITS images in them, and when I open the file browser it takes several minutes to load the file list. I'm assuming this is because it's scanning / caching FITS headers as it goes. A checkbox to tell CARTA to not do this and simply list the files so I can quickly open the one(s) that I'm interested in would be useful.

Thanks.

**Comment by kswang1029** [comment]
Please check File -> Preferences -> Global tab, then try options in the "File list" dropdown to see if it fits your need. Thanks.

![Screenshot 2023-09-15 at 15 24 01](https://github.com/CARTAvis/carta/assets/20819712/83fb0738-e911-4fde-8938-20f5ac36636a)

**Comment by IanHeywood** [comment]
Perfect, `Filter by extension` does the trick. Thanks for the swift response @kswang1029.
