### ISSUE TITLE
Feature request: add a button for a region shown in multiple frames

### ISSUE THREAD

**Issue by heh15** [CARTAvis/carta#21]
When I have multiple frames open and spatially aligned, I would like to create a region which is shown in multiple frames. Right now, I can only create a region in one frame, save it and import it into other frames respectively. It would be good to add a button to make the region shown in all of the spatially aligned frames simultaneously, like what CASA can do.

**Comment by kswang1029** [comment]
Thanks for sending us this feature request. This is under implementation and will be available in the next release (v1.4).

**Comment by heh15** [comment]
Thanks, that's great!
