### ISSUE TITLE
feature request: session sharing

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta#27]
from Lennart Heino

> I think it would be convenient to have a URL to directory mapping, so that I can send a link to my colleges that looks similar to:
`https://carta.idia.ac.za/carta_share/users/lennart/my-fits-file.fits`
And it will directly open the file.
It might be worthwhile to think about a more complex feature. Something like: "Safe session", which saves all the opened fits files and its view. With "Export session as link" one could map a hash of that session to a link for distribution:
`https://carta.idia.ac.za/session/<hashOfSessions938470981098f09jj3984>`

**Comment by veggiesaurus** [comment]
I suggest we start with adapting the existing URL query parameters (`?folder=<folder>&file=<file>`) to accept a full path in the `file` argument. e.g. `https://carta.idia.ac.za/?file=carta_share/users/lennart/my-fits-file.fits`

**Comment by veggiesaurus** [comment]
Closing in favour of https://github.com/CARTAvis/carta/issues/41
