### ISSUE TITLE
feature request: handle multi-extension images

### ISSUE THREAD

**Issue by teuben** [CARTAvis/carta#28]
If an image is "hidden" in the 2nd (or further) extension, carta seems confused.
Both ds9 and fv handle this transparently, and if we want community acceptance, this should be on our priority list.

**Comment by veggiesaurus** [comment]
@kswang1029 I thought we currently handle this? Do you have any multi-HDU examples to test?

**Comment by kswang1029** [comment]
We do but I will check again the case if image is not stored in the first HDU.

**Comment by veggiesaurus** [comment]
@teuben could you send us an example image which seems to confuse CARTA? I have an ADP image that has 32-bit images in the HDU1 and HDU2 extensions, and both images seem to load ok

**Comment by teuben** [comment]
I may have to eat my complaint, partially. I have two examples from the Hershell archive in https://www.astro.umd.edu/~teuben/data/
Those folks like to compress images (.gz), but although an error box comes up and says it cannot load the file, when I click on OK, it does present HDU 1 2 and 3 (where 0 is the pHDU).  On the first attempt the green box "connected to carta" also gave a failure, but after the first time it's been ok.

**Comment by veggiesaurus** [comment]
> I may have to eat my complaint, partially. I have two examples from the Hershell archive in https://www.astro.umd.edu/~teuben/data/
> Those folks like to compress images (.gz), but although an error box comes up and says it cannot load the file, when I click on OK, it does present HDU 1 2 and 3 (where 0 is the pHDU). On the first attempt the green box "connected to carta" also gave a failure, but after the first time it's been ok.

I'm able to load all three image HDUs of ngc4321_OI_cube.fits.gz. Am also able to load the table in our `dev` branch. Are these the compressed files you mentioned in #29? I can't seem to load the ngc4321_OI_m0.fits.gz file though :thinking: 

![image](https://user-images.githubusercontent.com/592504/86799880-b8f39f80-c072-11ea-88fd-0929e8c123b7.png)

**Comment by veggiesaurus** [comment]
Can we close this issue?
