### ISSUE TITLE
Feature Request: Tile Frames

### ISSUE THREAD

**Issue by drtobybrown** [CARTAvis/carta#3]
I frequently want to compare images and it would be very useful to have simultaneous viewing of multiple images/fits through the use of tiled frames.

This is [standard behaviour in DS9.](http://cxc.harvard.edu/ciao/threads/ds9/)

Thanks!

**Comment by veggiesaurus** [comment]
Thanks for the feature request @drtobybrown. This is something I've been hoping to implement for the 1.4 release, as it has been requested informally by a number of DS9 users. @Jordatious, this is what you were asking for as well, right?

For CARTA 1.3, we will support matching FoV of multiple images, but they will only be viewable simultaneously by overlaying contours (similar to casaviewer)

@kswang1029 I believe this is a bit different to a multi-panel viewer approach, and might be simpler to interact with.

**Comment by drtobybrown** [comment]
> For CARTA 1.3, we will support matching FoV of multiple images, but they will only be viewable simultaneously by overlaying contours (similar to casaviewer)


That's great (and will greatly increase CARTA's usability) but it's also good to hear that a side-by-side tile comparison may be coming in 1.4. I'm definitely in favor.

**Comment by Jordatious** [comment]
Yep this sounds like what I use ds9 for all the time. WCS-matched frames side by side. Also very keen to see this in CARTA!

**Comment by robertoabraham** [comment]
Just another expression of support for this. It would be very handy to have WCS-matched frames displayed next to each other.

**Comment by veggiesaurus** [comment]
In progress, should be complete (at least in some form) for the next public beta release next month. See https://github.com/CARTAvis/carta-frontend/issues/1259 for details.

**Comment by robertoabraham** [comment]
Thanks so much... CARTA is proving to be a real game changer!
