### ISSUE TITLE
Stokes colormap often missing

### ISSUE THREAD

**Issue by Jordatious** [CARTAvis/carta#32]
Often the Stokes analysis widget shows a colormap, but sometimes it doesn't seem to load, and just shows black data points. See example attached.

![image](https://user-images.githubusercontent.com/10542136/88167461-2a0d8800-cc19-11ea-8ebf-f549fb245244.png)

**Comment by veggiesaurus** [comment]
@Jordatious this has now been fixed and carta-testing has been updated to include this fix. Can you try reproduce the issue there?

**Comment by Jordatious** [comment]
This seems fixed now @veggiesaurus. So the colormap is frequency? Should we display that in some way?

**Comment by veggiesaurus** [comment]
Could display a colour bar 🤔

 closing this issue for now, if happens again, let me know
