### ISSUE TITLE
[1.5 suggestion] Requesting a simple spectral line fitting

### ISSUE THREAD

**Issue by cflee25** [CARTAvis/carta#39]
If times permitted, may I request to add a simple spectral line fitting with a simple gaussian profile, so that the users can retrieve the peak, center, and width of the line? I guess it should be mostly front-end work.

**Comment by keflavich** [comment]
I think the optimal approach for this would be to send the spectral data to python packages that already handle the fitting, i.e., astropy (https://docs.astropy.org/en/stable/modeling/) and specutils/spectral-cube.

**Comment by veggiesaurus** [comment]
For simple Gaussian fiitting, we can use [GSL](https://www.gnu.org/software/gsl/), which we already use for smoothing (via WebAssembly). For more specific spectral fitting, it might be a nice time to investigate frontend-based analytics plugins using [pyodide](https://github.com/iodide-project/pyodide), which would provide a python kernel running from within WebAssembly.

**Comment by kswang1029** [comment]
profile fitting to spectral profiles has been implemented.
