### ISSUE TITLE
missing beam

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta#4]
@drtobybrown let's continue this issue here.
Hi, 

As far as I can tell, CARTA does not display the beam size in its browser's file information panel nor as a beam ellipse for CASA image cubes (it does for moment maps). Can this be implemented/fixed?

I’ve attached two screen shots of the same image cube displayed in the viewer and Carta. The beam is there in the former but not the latter.

Cheers,
Toby
<img width="640" alt="cartaFileBrowser" src="https://user-images.githubusercontent.com/20819712/72487357-b729eb80-3848-11ea-892b-b18b24be0840.png">
![casaviewerFileBrowser](https://user-images.githubusercontent.com/20819712/72487358-b729eb80-3848-11ea-9096-f3c3919303ae.png)

**Comment by kswang1029** [comment]
@drtobybrown
We are wondering if your image cube has per-plane-beam (it appears so from your casaviewer screenshot which shows "median restoring beam" as an indicator of per-plane-beam)? i.e. Instead of having a fixed sized beam for all channel, each channel has its own beam size. Currently we don't support per-plane-beam yet but will support it soon (working in progress).

**Comment by drtobybrown** [comment]
> We are wondering if your image cube has per-plane-beam (it appears so from your casaviewer screenshot which shows "median restoring beam" as an indicator of per-plane-beam)?

Yep, this is the case. It would be very useful to have the same median beam size displayed in CARTA for cubes.

> Currently we don't support per-plane-beam yet but will support it soon (working in progress).

Great, thanks. Do you know when this is planned for? Is there a list of planned improvements/features somewhere?

**Comment by kswang1029** [comment]
Yes, our current dev branch shows median beam size and the support of per-plane-beam should be coming in the next release.

**Comment by veggiesaurus** [comment]
fixed in 2.0
