### ISSUE TITLE
Feature Request: Match Clip Min/Clip Max

### ISSUE THREAD

**Issue by keflavich** [CARTAvis/carta#42]
I'd like to view images on the same color stretch, with matched Clip Min / Clip Max & scaling.

It would be nice if this was also configurable from the debug scripted load.

**Comment by kswang1029** [comment]
do you mean https://github.com/CARTAvis/carta-frontend/issues/1089?

**Comment by keflavich** [comment]
Yes!

**Comment by kswang1029** [comment]
Good! This is scheduled in the next release (v2.0).

**Comment by keflavich** [comment]
OK, great!

Is there a release schedule?  I see a roadmap, but no schedule, here: https://cartavis.github.io/

**Comment by kswang1029** [comment]
it is still under discussions but probably sometime in Spring 2021.

**Comment by veggiesaurus** [comment]
closing as duplicate of https://github.com/CARTAvis/carta-frontend/issues/1089
