### ISSUE TITLE
problem about spectral line query on Ubuntu 18.04

### ISSUE THREAD

**Issue by acdo2002** [CARTAvis/carta#43]
Situation description: 
I build the frontend and backend on my Desktop Ubuntu 18.04, and I found that, after I insert spectral line query, the frontend shows (refer to the picture)
`curl_easy_perform() failed: Problem with the SSL CA cert (path? access rights?)`
Other function, like generate moment map works fine.

Several tests include: 
(1) update curl to the latest version -> problem is still there
(2) change to frontend/backend 1.4 release version -> problem is still there

I check CARTA app package, the spectral line query works fine on Ubuntu 18.04.
However I build the frontend and backend with the same way on my laptop Ubuntu 20.04, it works fine...

So I decide to upgrade my Desktop from 18.04 to 20.04 and check whether the problem can be solved.
Magically, spectral line query works fine on my Desktop 20.04. the problem solved...

I have no idea why the spectral line query does not work only on Ubuntu 18.04 (if I build the frontend & backend)?
![Screenshot from 2020-10-19 13-13-36](https://user-images.githubusercontent.com/34430648/97448853-0c646300-196c-11eb-97a2-fe735741553e.png)

**Comment by kswang1029** [comment]
Check libcurl, libssl and libcrypto version.

**Comment by acdo2002** [comment]
I have updated OpenSSL related libraries to the latest version, but the problem is still there until I upgrade to Ubuntu 20.04. 
Now I don't think downgrade is a good strategy (because the spectral line query function works fine now.), perhaps it could remind other people if they had the similar problem with building CARTA on Ubuntu 18.04? (no problem with app, only if users build frontend/backend by themselves)

Ubuntu 20.04 libraries version

> curl-config --version 
> libcurl 7.68.0
> openssl version
> OpenSSL 1.1.1f  31 Mar 2020

**Comment by acdo2002** [comment]
I think I found the possible(?) answer for this problem.
I remember my Desktop Ubuntu 18.04 the openssl version is 1.1.0. 
even I executed following command:

> sudo apt-get upgrade
> sudo apt-get update
> sudo apt-get install openssl

I should `wget` to the latest version 1.1.1 then build it directly (NOT use "traditional way" apt-get command)
[Reference1](https://stackoverflow.com/questions/51560964/how-to-upgrade-openssl-from-1-0-2g-to-1-1-0g-in-ubuntu-and-let-python-recognize)
[Reference2](https://cloudwafer.com/blog/installing-openssl-on-ubuntu-16-04-18-04/)

**Comment by veggiesaurus** [comment]
I'm not sure why we'd need to use openssl 1.1.1. does the backend no longer work in the 18.04 docker build?

**Comment by acdo2002** [comment]
I suppose openssl 1.1.0 is workable. Because many CARTA functions (e.g. moment generator, spectral profiler, animator playback...etc) all work well on 18.04. 

It only does not work with spectral line query (it relates to curl. so I uninstall-reinstall curl first! but problem is still there) on 18.04 with docker build. 
The spectral line query recovers when I upgrade to 20.04 (apt-get installed default is openssl 1.1.1).

**Comment by veggiesaurus** [comment]
@acdo2002 can you try this again now that we no longer need to link in crypto and ssl when building carta?

**Comment by acdo2002** [comment]
Hi Angus @veggiesaurus ,
I rebuild backend & frontend (all with the latest dev branch) on my Ubuntut 20.04 laptop. The spectral line query works fine. 
So far my laptop is already updated to 20.04 so I don't have any Ubuntu 18.04 machine to test it, sorry about this...

**Comment by veggiesaurus** [comment]
Perhaps we could try a docker container?

**Comment by kswang1029** [comment]
as a note: v1.4 in a 18.04 VM works fine.

**Comment by veggiesaurus** [comment]
so can we close this issue?

**Comment by acdo2002** [comment]
I am still trying a docker container...sorry this is my first time to try it...

**Comment by acdo2002** [comment]
@veggiesaurus 
Many thanks to Anthony's help. 
I built/run the docker container with Dockerfile-ubuntu-18.04 on my Ubuntu 20.04 laptop. (so it could be consider as the backend built on Ubuntu 18.04)
And spectral line query works fine as we expect.

Yes, now the issue can be closed!
