### ISSUE TITLE
Rectangular regions change between export and import

### ISSUE THREAD

**Issue by nindriolo** [CARTAvis/carta#44]
When I export rectangular regions (default CRTF and World) and then import them onto the same image, they have changed size and shape. Regions that are not rotated appear to shift slightly in position. Rectangular regions that are rotated will change size and shape. I do not see this problem with elliptical or freeform regions.

I am using CARTA v1.4 on MacOS 10.15.7

**Comment by kswang1029** [comment]
Thanks for pointing this out. We have noticed this issue and are working on it. https://github.com/CARTAvis/carta-backend/issues/541

**Comment by nindriolo** [comment]
Ok. I only see the offset issue mentioned in the linked ticket. In case it's useful to document the changing region size and shape when a rectangular region is rotated as well, I've attached a figure showing the issue. The original region is shown in red, and the region shown in blue is what I see after exporting then importing.
![CARTAexample](https://user-images.githubusercontent.com/22348765/98692929-a994a380-233d-11eb-87aa-d3c15e32df5c.png)

**Comment by Jordatious** [comment]
@kswang1029, @veggiesaurus and I have investigated this issue a bit further now, prompted by @pjmac1105's email to the helpdesk. As noted above, it only affects rectangle regions, not ellipses or polygons. It seems to randomly change the shape / axes and possibly rotate it. It's currently present for both v1.4 and dev. It's only present when using world coordinates, at least for FK5, ICRS and Galactic, but isn't present for pixel coordinates.

Angus and I agree it's different to issue https://github.com/CARTAvis/carta-backend/issues/541. It's not a small (pixel-scale) error, but much larger. 

Let me know if you'd like me to attach an example image and region. But I think you'll find it's very easy to reproduce.

**Comment by Jordatious** [comment]
Sorry, I should mention, it's the same issue for DS9 and CARTA region format.

**Comment by kswang1029** [comment]
the issue is deeper in casacore (ref. https://github.com/CARTAvis/carta-backend/issues/541#issuecomment-784584911)

UPDATE: sorry I got issues mixed up🙈 not 541

**Comment by veggiesaurus** [comment]
> the issue is deeper in casacore (ref. [CARTAvis/carta-backend#541 (comment)](https://github.com/CARTAvis/carta-backend/issues/541#issuecomment-784584911))

I don't think this is the same issue though. This occurs when importing and exporting to the same image, and it's not just a small single-pixel offset, it's a completely different shape.

**Comment by kswang1029** [comment]
@acdo2002 please help to verify if the fix works. Thanks.
