### ISSUE TITLE
Encourage server installations

### ISSUE THREAD

**Issue by Kechil** [CARTAvis/carta#51]
This will be ultimately blocked by Kuo-Song's documentation update which he will do during code freeze. However we need some interim documentation (TBD) for sys admin people.

The tasks in this issue are to encourage sys admins in institutions to install CARTA on their servers. 
https://docs.google.com/spreadsheets/d/1_X-CNxrk84rYUP_AfoJK3qSFei5eItipL0dlYEeIttQ/edit#gid=0

**Comment by robsimmonds** [comment]
What we need to do is stop telling people to use the desktop packaging everywhere, particularly in on clusters where this is not secure. If we point out how much more secure the version that is started using the node server is, and how it offers ease-of-use and performances advantages, then we will not need to encourage anyone to use this approach. They will be asking their sys admins to install it this way.
