### ISSUE TITLE
Rectangle side-dragger snaps back to center when zooming

### ISSUE THREAD

**Issue by nbrunett** [CARTAvis/carta#52]
I've noticed that the white square that denotes the place that I can grab the side of a rectangular region for resizing can be slid along that edge, which is nice. However, if I have slid that square somewhere that is not the center of that side of the rectangle and then zoom, the white square goes back to the center of that side.

It would be better if the square stayed where it was last moved to when you start zooming in and/or out. The use case for this is if you are zoomed into a large image, your field of view may not include the center of the side of the region you want to adjust. As it is now, I would have to pan over to the center of the image to pull the square to the part of the image I want to view while I am adjusting the region.

Let me know if you need any more information or if this is unclear. Thanks.

**Comment by kswang1029** [comment]
It is actually a bug. The side control points should stay at the center of a side. Will address this issue with https://github.com/CARTAvis/carta-frontend/issues/1278

**Comment by nbrunett** [comment]
I’ll just add that if you have to keep using the white squares for handles that I think it would be useful for those side ones to be able to slide. If they are stuck in the center of the side then I don’t see a convenient way to move a side when zoomed in where you can’t see the center of the side. Just a suggestion.

**Comment by kswang1029** [comment]
fixed.
