### ISSUE TITLE
Offset in selected region vs. displayed region for rectangles

### ISSUE THREAD

**Issue by e-koch** [CARTAvis/carta#57]
I recently encountered this issue (see screenshot 1 below) with CARTA v1.4. The histogram shows that a bunch of 0s are included in the region, but the region displayed in the viewer doesn't overlap with empty regions in the image.

I suspect it may have to do with the orientation of the rectangle because moving the region over in screenshot 2 removes the spike at 0 in the histogram.

Screenshot 1 with problem:
![carta_rectangle_offset_withist](https://user-images.githubusercontent.com/3255771/106331929-c614ed80-6253-11eb-87e1-c43a373dc0a2.png)

Screenshot 2 without problem:
![carta_rectangle_offset_withhist_2](https://user-images.githubusercontent.com/3255771/106332198-4cc9ca80-6254-11eb-9d1d-80dceaaaf878.png)

**Comment by kswang1029** [comment]
Thanks for the feedback. We are addressing this bug in https://github.com/CARTAvis/carta-backend/issues/689

**Comment by kswang1029** [comment]
fixed
