### ISSUE TITLE
WCS read failure breaks spectral extraction

### ISSUE THREAD

**Issue by keflavich** [CARTAvis/carta#58]
I tried loading a cube that results in an AST error, as shown in this log:
```
compute
Compute module loaded
ast
AST library loaded
network
Connected to server ws://localhost:35537 with session ID 4
file
Loaded file Cycle6_GR_OT_06_0173_AHarris_SgrA_CII.cube.fits with dimensions 253×377×10389
ast
Problem processing WCS info in file Cycle6_GR_OT_06_0173_AHarris_SgrA_CII.cube.fits
ast
Problem processing WCS info in file Cycle6_GR_OT_06_0173_AHarris_SgrA_CII.cube.fits
```

After this, there are two problems:
(1) The cursor location doesn't update
(2) Spectral extraction no longer works

Both problems are shown in this figure
![image](https://user-images.githubusercontent.com/143715/107516550-92529580-6b7a-11eb-8711-a41e7d4bbc76.png)
the cursor is fixed with `f`, and I can't move it (even after un-fixing).  The spectral extraction is blank.

The problem remains if I open a different cube; I have to totally restart the CARTA server to fix it.

**Comment by keflavich** [comment]
The header is:
```
SIMPLE  =                    T         /                                        
BITPIX  =                  -64                                                  
NAXIS   =                    3                                                  
NAXIS1  =                  238                                                  
NAXIS2  =                  292                                                  
NAXIS3  =                  964                                                  
DATAMIN = -0.5161565399170E+02         /                                        
DATAMAX =  0.4070548706055E+03         /                                        
BUNIT   = 'K'                          /                                        
OBJECT  = 'SGRB2_CMZM50'                                                        
RA      =  0.2668525000000E+03         / Right Ascension                        
DEC     = -0.2838786100000E+02         / Declination                            
LINE    = 'CII_L   '                                                            
ALTRPIX =  0.2617159423828E+03         /                                        
ALTRVAL =  0.1900853875436E+13         /                                        
RESTFREQ=        1900536900000                                                  
VELO-LSR= -0.5000000000000E+05         /                                        
VELREF  =                  257         /                                        
BMAJ    =  0.4128529188155E-02         /                                        
BMIN    =  0.4128529188155E-02         /                                        
BPA     =  0.0000000000000E+00         /                                        
ORIGIN  = 'GILDAS Consortium  '        /                                        
DATE    = '2018-09-30T00:00:00.00'     / Date written                           
MISSN-ID= '2018-06-06_GR_F466'                                                  
ASSC_MSN= '2018-06-06_GR_F466,2018-06-05_GR_F465,2018-06-20_GR_F473,2018-06-22&'
CONTINUE  '_GR_F475'                                                            
EXPTIME =    380302.2151118523                                                  
TELEL   =    47.74472543134225                                                  
AZIMUTH =    176.3217454388875                                                  
LST-OBS = '17:08:25'                                                            
VELDEF  = 'RADI-LSR'                                                            
IMAGFREQ=      1903536.2303499                                                  
ASSC_FRQ=            1900536.9                                                  
RVSYS   =                -50.0                                                  
VELRES  =     0.03849595785141                                                  
FREQRES =    -0.24410000443459                                                  
FREQOFFS=          -500.000394                                                  
CHPANGLE=                185.0                                                  
CHPAMP1 =                  0.0                                                  
CHPFREQ =                 10.0                                                  
BACKEND = 'LFAV    '                                                            
FRONTEND= 'LFAV_PX00'                                                           
HEADING =     42.7182553565432                                                  
GRDSPEED=    799.4524227590085                                                  
TEMPSEC1=    236.7268250213849                                                  
TEMPPRI1=                  0.0                                                  
TAMBSOFI=    240.6206582034699                                                  
LAMBDA  =    4.657454742178185                                                  
LAMOFF  =  -0.0104558682042198                                                  
BETA    =  -0.4954616420484908                                                  
BETOFF  = -0.01689478106887623                                                  
UTCSTART= '08:17:03'                                                            
UTCEND  = '18:16:43'                                                            
INSTRUME= 'GREAT   '                                                            
LAT_STA =   -50.57498219996788                                                  
LON_STA =   -153.3661300127321                                                  
OPERATOR= 'ShannonSam'                                                          
OBSERVER= 'Robert  '                                                            
DATASRC = 'ASTRO   '                                                            
PLANID  = '06_0157 '                                                            
AOR_ID  = '06_0157_33'                                                          
ASSC_AOR= '06_0157_33,06_0157_28,06_0157_30,06_0157_31,06_0157_32,06_0157_47,0&'
CONTINUE  '6_0173_42,06_0173_46'                                                
CLS_IDX =              10675.0                                                  
SPECTEL1= 'GRE_LFA '                                                            
SPECTEL2= 'NONE    '                                                            
INSTCFG = 'DUAL_CHANNEL'                                                        
OBS_ID  = 'Cycle6_GR_OT_06_0157_RGuesten_SgrC_CII.lmv.fits'                     
FILENAME= 'Cycle6_GR_OT_06_0157_RGuesten_SgrC_CII.lmv.fits'                     
TELRA   =    17.75022819205028                                                  
TELDEC  =   -29.35586065104419                                                  
OBSTYPE = 'OBJECT  '                                                            
PROCSTAT= 'LEVEL_4 '                                                            
N_SPEC  =            1267674.0                                                  
HEADSTAT= 'MODIFIED'           / Header status                                  
BEAM    = 'Beam: BMAJ=14.862705077358 arcsec BMIN=14.862705077358 arcsec &'     
CONTINUE  'BPA=0.0 deg'                                                         
WCSAXES =                    3 / Number of coordinate axes                      
CRPIX1  =      -184.0453408311 / Pixel coordinate of reference point            
CRPIX2  =       620.1350057987 / Pixel coordinate of reference point            
CRPIX3  =       261.7159423828 / Pixel coordinate of reference point            
CDELT1  =    -0.00195833329593 / [deg] Coordinate increment at reference point  
CDELT2  =     0.00195833329593 / [deg] Coordinate increment at reference point  
CDELT3  =      0.3849593997002 / [m/s] Coordinate increment at reference point  
CUNIT1  = 'deg'                / Units of coordinate increment and value        
CUNIT2  = 'deg'                / Units of coordinate increment and value        
CUNIT3  = 'km s-1  '           / Units of coordinate increment and value        
CTYPE1  = 'RA---SFL'           / Right ascension, Sanson-Flamsteed projection   
CTYPE2  = 'DEC--SFL'           / Declination, Sanson-Flamsteed projection       
CTYPE3  = 'VRAD'               / Radio velocity (linear)                        
CRVAL1  =             266.8525 / [deg] Coordinate value at reference point      
CRVAL2  =           -28.387861 / [deg] Coordinate value at reference point      
CRVAL3  =     -49.999999999981 / [m/s] Coordinate value at reference point      
PV1_0   =                  1.0 / [m/s] Coordinate value at reference point      
PV1_1   =                  0.0 / [deg] Native longitude of the reference point  
PV1_2   =           -28.387861 / [deg] Native latitude  of the reference point  
LONPOLE =                  0.0 / [deg] Native longitude of celestial pole       
LATPOLE =                 90.0 / [deg] Native latitude of celestial pole        
RESTFRQ =      1900536900000.0 / [Hz] Line rest frequency                       
MJDREF  =                  0.0 / [d] MJD of fiducial time                       
DATE-OBS= '2018-06-05T15:57:59' / ISO-8601 time of observation                  
MJD-OBS =      58274.665266204 / [d] MJD of observation                         
RADESYS = 'FK5'                / Equatorial coordinate system                   
EQUINOX =               2000.0 / [yr] Equinox of equatorial coordinates         
SPECSYS = 'LSRK'               / Reference frame of spectral coordinates        
HISTORY                                                                         
HISTORY Headers updated by rarneson, 2020-02-18T14:00:33                        
HISTORY   TELRA: 17.75022819205028 -> 17.75022819                               
HISTORY   TELDEC: -29.35586065104419 -> -29.35586065                            
HISTORY                                                                         
HISTORY                                                                         
HISTORY Headers updated by rarneson, 2020-02-19T12:28:13                        
HISTORY   FILENAME: Cycle6_GR_OT_06_0157_RGuesten_SgrC_CII.great.fits -> Cycle6_
HISTORY GR_OT_06_0157_RGuesten_SgrC_CII.lmv.fits                                
HISTORY   OBS_ID: Cycle6_GR_OT_06_0157_RGuesten_SgrC_CII.great.fits -> Cycle6_GR
HISTORY _OT_06_0157_RGuesten_SgrC_CII.lmv.fits                                  
HISTORY                                                                         
COMMENT Original Unit=m / s                                                     
COMMENT Original Type=VRAD           
```

**Comment by keflavich** [comment]
Correction: restarting the browser frontend fixes the problem if I load a well-behaved cube; I don't have to restart the backend.

**Comment by kswang1029** [comment]
if we put the header to http://starlink.eao.hawaii.edu/cgi-bin/ast/fits-plotter and make a plot, it works
![image](https://user-images.githubusercontent.com/20819712/107521961-1f830200-6bee-11eb-953c-a5cf056d5013.png)

We will need to investigate this. @keflavich Would you mind sharing a small sub-image for diagnostics? If it is not appropriate we can make a mock-up one based on the header.

**Comment by keflavich** [comment]
The data I was looking at came from the SOFIA archive.  This link _may_ connect to the appropriate data set... unfortunately I can't find a direct FITS link.

https://irsa.ipac.caltech.edu/applications/sofia/?__action=SofiaSearch&request=%7B%22startIdx%22%3A0%2C%22pageSize%22%3A100%2C%22id%22%3A%22SofiaQuery%22%2C%22searchtype%22%3A%22SINGLE%22%2C%22proposalSection%22%3A%22closed%22%2C%22observationSection%22%3A%22closed%22%2C%22instrument%22%3A%22GREAT%22%2C%22configuration%22%3A%22%22%2C%22bandpass_name%22%3A%22%22%2C%22instrumentSection%22%3A%22open%22%2C%22processing%22%3A%22LEVEL_4%22%2C%22obstype%22%3A%22%22%2C%22dataProductSection%22%3A%22open%22%2C%22UserTargetWorldPt%22%3A%22266.41683%3B-29.0078%3BEQ_J2000%3Bsgr%20a*%3Bned%22%2C%22radius%22%3A%221%22%2C%22META_INFO%22%3A%7B%22title%22%3A%22SofiaQuery%22%2C%22tbl_id%22%3A%22tbl_id-c2138-57%22%7D%2C%22tbl_id%22%3A%22tbl_id-c2138-57%22%2C%22spectral_element%22%3A%22%22%7D&options=%7B%22logHistory%22%3Atrue%7D

edit: specifically, these:
```
06_0157_20
2018-06-15_GR_F470
SGRB2_CMZ_0
266.6533426
-28.7642871
GREAT
DUAL_CHANNEL
GRE_LFA
CII_L
OBJECT
LEVEL_4

06_0157_20
2018-06-15_GR_F470
SGRB2_CMZ_0
266.6533426
-28.7642871
GREAT
DUAL_CHANNEL
GRE_LFA
CII_L
OBJECT
LEVEL_4
```

**Comment by kswang1029** [comment]
https://irsa.ipac.caltech.edu/data/SOFIA/GREAT/L4/p9108/data/Cycle6_GR_OT_06_0173_AHarris_CMZ_G359P9.great.tar this I think

**Comment by kswang1029** [comment]
https://irsa.ipac.caltech.edu/data/SOFIA/GREAT/L4/p9112/data/Cycle6_GR_OT_06_0173_AHarris_SgrA_CII.lmv.fits this? (7.93 GB...)

**Comment by keflavich** [comment]
yes, that.  How did you navigate to that?

**Comment by kswang1029** [comment]
search "06_0157_20", on the right hand side scroll down :)  
![Screen Shot 2021-02-10 at 11 01 55 PM](https://user-images.githubusercontent.com/20819712/107527667-ffeed800-6bf3-11eb-893c-d290c3560dbf.png)

**Comment by keflavich** [comment]
This one too, it's a little smaller.  Thanks for pointing me in the right direction on the archive page... that is _much_ easier than their download system!
https://irsa.ipac.caltech.edu/data/SOFIA/GREAT/L4/p9109/data/Cycle6_GR_OT_06_0157_RGuesten_SgrC_CII.lmv.fits (536MB)

**Comment by kswang1029** [comment]
Some more info about the issue:

![Screen Shot 2021-02-10 at 11 27 11 PM](https://user-images.githubusercontent.com/20819712/107531811-2878d100-6bf8-11eb-9c50-127190c31c62.png)

The issue remains in the current dev+dev. Also tried origin/jason/issue_1127_4 6ff1a91 and the issue remains. @veggiesaurus @duidae

**Comment by kswang1029** [comment]
> 2021-02-10 15:44:29	WARN	importfits::FITSCoordinateUtil::fromFITSHeader	Note: The GLS projection is deprecated. Use SFL instead.
2021-02-10 15:44:29	WARN	importfits::FITSCoordinateUtil::fromFITSHeader	Note: The GLS projection is deprecated. Use SFL instead.
2021-02-10 15:44:29	WARN	importfits::ImageFITSConverterImpl::FITSToImage (file ../../casacore/images/Images/ImageFITSConverter.tcc, line 74)	FITS unit "K (Tmb)" unknown to CASA, was truncated to "K ".
2021-02-10 15:44:31	SEVERE	importfits::image::open (file ../../tools/images/image_cmpt.cc, line 4134)	Exception Reported: wcs wcsset_error: Ill-conditioned coordinate transformation parameter
2021-02-10 15:44:31	SEVERE	importfits::::	*** Error *** wcs wcsset_error: Ill-conditioned coordinate transformation parameter
2021-02-10 15:44:31	SEVERE	importfits::::	An error occurred running task importfits.

this is potentially a backend issue as when I tried to use CASA to convert the FITS image to CASA format, there are errors messages as the above. But somehow the CARTA backend successfully returns a header after casacore parsing.  @pford

**Comment by keflavich** [comment]
Thanks @kswang1029.  Do you know what the best workaround is?  I've tried reprojecting to a valid WCS using astropy tools, but so far unsuccessfully.

GILDAS-CLASS sometimes produces headers like these, and they're present in the SOFIA archive (and others), so it would be good to have a clear workaround in place even if this gets solved, since clearly it's affecting old CASA and CARTA versions.

**Comment by kswang1029** [comment]
I tried:
- convert to miriad format and use cgdisp to view (working; but lots of headers are gone) but with CARTA the image header cannot be parsed. Converting miriad format back to fits with MIRIAD-fits task results in the same issue.
- use KARMA-kvis to view the FITS image (working) and save as a new FITS for CARTA to view (same issue).

Need more thoughts....

**Comment by keflavich** [comment]
I tried manually editing the header, removing the PV keywords, correcting the BUNIT error (`BUNIT = 'K'` now), setting the restfrq properly (it was originally in MHz, but FITS standard says it should be Hz), but none of these fixed the problem, which makes me think that the fundamental issue is in the `SFL` projection.  Not sure, though.

**Comment by veggiesaurus** [comment]
> Some more info about the issue:
> 
> ![Screen Shot 2021-02-10 at 11 27 11 PM](https://user-images.githubusercontent.com/20819712/107531811-2878d100-6bf8-11eb-9c50-127190c31c62.png)
> 
> The issue remains in the current dev+dev. Also tried origin/jason/issue_1127_4 6ff1a91 and the issue remains. @veggiesaurus @duidae

@kswang1029 the header files are being changed by casacore. The actual header shown using `fitshdr` has `GLS` projection, but the one being sent to the frontend has `SFL`. Some output from the backend:
```
2021-02-10 16:43:46	WARN	FITSCoordinateUtil::fromFITSHeader	Note: The GLS projection is deprecated. Use SFL instead.
2021-02-10 16:43:46	WARN	FITSCoordinateUtil::fromFITSHeader	Note: The GLS projection is deprecated. Use SFL instead
```

The reason AST is then bombing out is that only the `CTYPE` is changed, but the `CRVAL`, `CDELT` and `CRPIX` values are unmodified, so the WCS stuff is now corrupt. 

I think the solution is (as @pford suggested) to use AST in the backend codebase as well, and send the raw headers to the frontend, rather than having them go through casacore.

**Comment by pford** [comment]
The reason that casacore is used for the headers was the requirement early in carta development (backend issue [13](https://github.com/CARTAvis/carta-backend/issues/13)) for a unified FITS header display.

**Comment by kswang1029** [comment]
@keflavich Using Starlink to save the fits image as a new one seems to work, but I noticed that it also converts GLS to SFL. 

http://starlink.eao.hawaii.edu/docs/sun55.htx/sun55.html

try 
`fits2ndf Cycle6_GR_OT_06_0157_RGuesten_SgrC_CII_lmv.fits Cycle6_GR_OT_06_0157_RGuesten_SgrC_CII_lmv`
then
`ndf2fits Cycle6_GR_OT_06_0157_RGuesten_SgrC_CII_lmv.sdf Cycle6_GR_OT_06_0157_RGuesten_SgrC_CII_lmv_v2.fits`
then in CARTA we see
![Cycle6_GR_OT_06_0157_RGuesten_SgrC_CII_lmv_v2 fits-image-2021-2-11-13-41-6](https://user-images.githubusercontent.com/20819712/107605737-ff475780-6c6e-11eb-9790-262a06e9494b.png)
![Cycle6_GR_OT_06_0157_RGuesten_SgrC_CII_lmv_v2 fits-image-2021-2-11-13-41-0](https://user-images.githubusercontent.com/20819712/107605752-08d0bf80-6c6f-11eb-8f93-c5697aa49d33.png)

**Comment by keflavich** [comment]
Could you post the resulting header here?  I don't have starlink installed anywhere

**Comment by kswang1029** [comment]
read via ds9

> SIMPLE  =                    T / file does conform to FITS standard             
BITPIX  =                  -64 / number of bits per data pixel                  
NAXIS   =                    4 / number of data axes                            
NAXIS1  =                  238 / length of data axis 1                          
NAXIS2  =                  292 / length of data axis 2                          
NAXIS3  =                  964 / length of data axis 3                          
NAXIS4  =                    1 / length of data axis 4                          
EXTEND  =                    T / FITS dataset may contain extensions            
COMMENT   FITS (Flexible Image Transport System) format is defined in 'Astronomy
COMMENT   and Astrophysics', volume 376, page 359; bibcode: 2001A&A...376..359H 
OBJECT  = 'SGRB2_CMZM50'       / Title of the dataset                           
BUNIT   = 'K (Tmb) '           / Units of the primary array                     
DATE    = '2021-02-11T05:40:10' / file creation date (YYYY-MM-DDThh:mm:ss UT)   
ORIGIN  = 'GILDAS Consortium  '                                                 
BSCALE  =                  1.0 / True_value = BSCALE * FITS_value + BZERO       
BZERO   =                  0.0 / True_value = BSCALE * FITS_value + BZERO       
HDUCLAS1= 'NDF     '           / Starlink NDF (hierarchical n-dim format)       
HDUCLAS2= 'DATA    '           / Array component subclass                       
HDSTYPE = 'NDF     '           / HDS data type of the component                 
DATAMIN =       -51.6156539917                                                  
DATAMAX =       407.0548706055                                                  
CTYPE1  = 'RA---SFL'           / Type of co-ordinate on axis 1                  
CRVAL1  =             266.8525 / Value at ref. pixel on axis 1                  
CDELT1  = -0.00195833329593002 / Pixel size on axis 1                           
CRPIX1  =          -184.045341 / Reference pixel on axis 1                      
CTYPE2  = 'DEC--SFL'           / Type of co-ordinate on axis 2                  
CRVAL2  =           -28.387861 / Value at ref. pixel on axis 2                  
CDELT2  =  0.00195833329593008 / Pixel size on axis 2                           
CRPIX2  =           620.135006 / Reference pixel on axis 2                      
CTYPE3  = 'VRAD    '           / Type of co-ordinate on axis 3                  
CRVAL3  =    -49890.6246938865 / Value at ref. pixel on axis 3                  
CDELT3  =     384.959399668561 / Pixel size on axis 3                           
CRPIX3  =                262.0 / Reference pixel on axis 3                      
CTYPE4  = 'AXIS4   '           / Type of co-ordinate on axis 4                  
CRVAL4  =                  1.0 / Value at ref. pixel on axis 4                  
CDELT4  =                  1.0 / Pixel size on axis 4                           
CRPIX4  =                  1.0 / Reference pixel on axis 4                      
RA      =             266.8525 / Right Ascension                                
DEC     =           -28.387861 / Declination                                    
EQUINOX =               2000.0 / [yr] Epoch of reference equinox                
LINE    = 'CII_L   '                                                            
ALTRPIX =       261.7159423828                                                  
ALTRVAL =      1900853875436.0                                                  
VELO-LSR=             -50000.0                                                  
VELREF  =                  257                                                  
SPECSYS = 'LSRK    '           / Standard of rest for spectral axis             
BMAJ    =    0.004128529188155                                                  
BMIN    =    0.004128529188155                                                  
BPA     =                  0.0                                                  
MISSN-ID= '2018-06-06_GR_F466'                                                  
ASSC_MSN= '2018-06-06_GR_F466,2018-06-05_GR_F465,2018-06-20_GR_F473,2018-06-22&'
CONTINUE  '_GR_F475'                                                            
EXPTIME =     380302.215111852                                                  
TELEL   =     47.7447254313423                                                  
AZIMUTH =     176.321745438887                                                  
LST-OBS = '17:08:25'                                                            
VELDEF  = 'RADI-LSR'                                                            
IMAGFREQ=     1903536.23034789 / [Hz] Image frequency                           
ASSC_FRQ=            1900536.9                                                  
RVSYS   =                -50.0                                                  
VELRES  =     0.03849595785141                                                  
FREQRES =              -0.2441                                                  
FREQOFFS=               -500.0                                                  
CHPANGLE=                185.0                                                  
CHPAMP1 =                  0.0                                                  
CHPFREQ =                 10.0                                                  
BACKEND = 'LFAV    '                                                            
FRONTEND= 'LFAV_PX00'                                                           
HEADING =     42.7182553565432                                                  
GRDSPEED=     799.452422759009                                                  
TEMPSEC1=     236.726825021385                                                  
TEMPPRI1=                  0.0                                                  
TAMBSOFI=      240.62065820347                                                  
LAMBDA  =     4.65745474217819                                                  
LAMOFF  =  -0.0104558682042198                                                  
BETA    =   -0.495461642048491                                                  
BETOFF  =  -0.0168947810688762                                                  
UTCSTART= '08:17:03'                                                            
UTCEND  = '18:16:43'                                                            
DATE-OBS= '2018-06-05T15:57:59.000' / Date of observation                       
CUNIT3  = 'm/s     '           / Units for axis 3                               
MJD-OBS =     58274.6652662037 / Modified Julian Date of observation            
RADESYS = 'FK5     '           / Reference frame for RA/DEC values              
VELOSYS =    -17323.0617443905 / [m/s] Topo. apparent velocity of rest frame    
RESTFRQ =            1900536.9 / [Hz] Rest frequency                            
INSTRUME= 'GREAT   '                                                            
LAT_STA =    -50.5749821999679                                                  
LON_STA =    -153.366130012732                                                  
OPERATOR= 'ShannonSam'                                                          
OBSERVER= 'Robert  '                                                            
DATASRC = 'ASTRO   '                                                            
PLANID  = '06_0157 '                                                            
AOR_ID  = '06_0157_33'                                                          
ASSC_AOR= '06_0157_33,06_0157_28,06_0157_30,06_0157_31,06_0157_32,06_0157_47,0&'
CONTINUE  '6_0173_42,06_0173_46'                                                
CLS_IDX =              10675.0                                                  
SPECTEL1= 'GRE_LFA '                                                            
SPECTEL2= 'NONE    '                                                            
INSTCFG = 'DUAL_CHANNEL'                                                        
OBS_ID  = 'Cycle6_GR_OT_06_0157_RGuesten_SgrC_CII.lmv.fits'                     
FILENAME= 'Cycle6_GR_OT_06_0157_RGuesten_SgrC_CII.lmv.fits'                     
TELRA   =     17.7502281920503                                                  
TELDEC  =    -29.3558606510442                                                  
OBSTYPE = 'OBJECT  '                                                            
PROCSTAT= 'LEVEL_4 '                                                            
N_SPEC  =            1267674.0                                                  
HEADSTAT= 'MODIFIED'           / Header status                                  
HISTORY                                                                         
HISTORY Headers updated by rarneson, 2020-02-18T14:00:33                        
HISTORY   TELRA: 17.75022819205028 -> 17.75022819                               
HISTORY   TELDEC: -29.35586065104419 -> -29.35586065                            
HISTORY                                                                         
HISTORY                                                                         
HISTORY Headers updated by rarneson, 2020-02-19T12:28:13                        
HISTORY   FILENAME: Cycle6_GR_OT_06_0157_RGuesten_SgrC_CII.great.fits -> Cycle6_
HISTORY GR_OT_06_0157_RGuesten_SgrC_CII.lmv.fits                                
HISTORY   OBS_ID: Cycle6_GR_OT_06_0157_RGuesten_SgrC_CII.great.fits -> Cycle6_GR
HISTORY _OT_06_0157_RGuesten_SgrC_CII.lmv.fits                                  
HISTORY                                                                                                                                                     
CHECKSUM= '5HjWAFjW7FjWAFjW'   / HDU checksum updated 2021-02-11T05:40:12       
DATASUM = '1259351660'         / data unit checksum updated 2021-02-11T05:40:12 
END

**Comment by keflavich** [comment]
OK, thanks - this confirms that the minimalist fix of `s/GLS/SFL/` in the header solves it.  After doing that, CARTA shows the spectrum just fine.  I can't say whether the spatial coordinates are still correct....

**Comment by veggiesaurus** [comment]
@kswang1029 is this fixed with the recent FITS header changes?

**Comment by kswang1029** [comment]
Looks like it! 

![Screen Shot 2021-07-15 at 9 57 07 AM](https://user-images.githubusercontent.com/20819712/125715900-5ad813e7-eb8d-4aee-be4c-7d20358d768a.png)
