### ISSUE TITLE
feature request: option to save statistics along with regions

### ISSUE THREAD

**Issue by pmanojlovic** [CARTAvis/carta#59]
Or some way to add these as columns to an open catalogue, though catalogues can't be exported at the moment. This would be especially useful to get flux densities for regions around many objects with complex morphologies.

**Comment by kswang1029** [comment]
Do you mean this https://github.com/CARTAvis/carta-frontend/issues/1262 ? If so it should be available in the next release before summer

**Comment by pmanojlovic** [comment]
That sounds great, just want to make sure it can be saved for all regions at once.

**Comment by kswang1029** [comment]
Regarding "saving for all regions at once", we plan to do this via the scripting interface which is under development. In the next release, we will need to save it one by one via the GUI.

**Comment by kswang1029** [comment]
implemented. region statistics can be exported as a tsv file with info regarding image name and region properties.
