### ISSUE TITLE
Question: catalog file format or example

### ISSUE THREAD

**Issue by tammojan** [CARTAvis/carta#61]
I'd like to try the new feature of catalog overlay. However I cannot find documentation of the file format of the catalog that is required, other than that it should be fits. Is the format documented, or is an example catalog available?

**Comment by kswang1029** [comment]
CARTA supports the catalog file format in VOTable and FITS. It is documented as part of the in-app help manual.
![Screen Shot 2021-03-03 at 11 03 14 AM](https://user-images.githubusercontent.com/20819712/109746429-56a66b00-7c10-11eb-8cdd-9dc22c7d0db4.png)
and in the online manual as well. 
https://carta.readthedocs.io/en/latest/catalogue_visualization.html

**Comment by kswang1029** [comment]
example catalog file in the FITS format: https://www.lofar-surveys.org/lba.html

**Comment by tammojan** [comment]
Thank you! I don't know how wide-spread the FITS standard for source catalogues is, maybe it would help to mention the required columns, or have a link to the file format, in the documentation.
