### ISSUE TITLE
Register all appended images to the same zoom, pan and colour levels

### ISSUE THREAD

**Issue by sanbw** [CARTAvis/carta#65]
This is a request to register *all* appended images to the same zoom, pan and colour levels.  Currently each image independently zoomed and panned and the display minimum and maximum values are independently set.  This makes is nearly impossible to view same region of the images, with the same coordinates in a zoomed and panned manner.  Because of this, appended images have a limit utility.

The pixel values under the mouse pointer are also displayed only for the visible image.  Those should also, optionally, displayed for *all* the appended images.

**Comment by kswang1029** [comment]
The requested feature (except color levels) should have been supported in _v1.4_. Once multiple images are loaded in CARTA, the "Image List" widget should list them all. By using the "XY" button in the "Matching" column, images will be matched _spatially_. If cubes are loaded, the "Z" button will enable _spectral_ matching too. Please refer to the following video to see how it works or refer to the user manual https://carta.readthedocs.io/en/latest/image_visualization.html#match-images-in-world-coordinates .


https://user-images.githubusercontent.com/20819712/110231464-d3a84c00-7f52-11eb-80a8-d8c3f2c5609f.mp4



The color level matching (only the bound values, not scaling nor colormap) will be supported in the coming spring release.

Regarding the cursor value for _all_ matched images, it is on our plan https://github.com/CARTAvis/carta-frontend/issues/1146. It would likely happen in the fall release.

**Comment by sanbw** [comment]
Thanks.  Matching along the XY axis using the Matching "XY" button does what I was looking for.
