### ISSUE TITLE
Feature request: match render configuration across images

### ISSUE THREAD

**Issue by o-smirnov** [CARTAvis/carta#69]
When comparing multiple images, it is often very useful to lock the render config (clip min/max, etc.) together. Sort of the equivalent of spatial matching. Could this be implemented as an extra control in the "Matching" column of the image list?

**Comment by veggiesaurus** [comment]
Also implemented in 2.0 😊 matching render config matches min, max and scaling values.

**Comment by o-smirnov** [comment]
He he, you're anticipating my every wish here. I'll try to make my third one a bit more challenging!

**Comment by Jordatious** [comment]
Yep this is already implemented in dev as per my identical request in https://github.com/CARTAvis/carta-frontend/issues/1089. Where are you using CARTA? You may be able to access the dev version.

**Comment by o-smirnov** [comment]
On my own machines and containers... but I'll go a long way out of my way for this particular feature -- can I build the dev version myself? Is it a matter of checking out particular branches and following the build instructions?

**Comment by confluence** [comment]
If you're using Ubuntu Focal, you can install a packaged development version [from the PPA here](https://launchpad.net/~cartavis-team/+archive/ubuntu/carta) (Bionic will eventually also be provided). The `carta-beta` metapackage installs the backend and frontend packages.

If you install directly on a Focal desktop you can then launch `carta` on the commandline or from the GUI (a desktop file is installed by the backend package; it runs the backend in a terminal which you can later use to close it).

The development backend serves its own frontend files (assuming that it can find them), so no additional setup is needed for this; it should just work. By default it has Jupyter-like behaviour -- it logs a URL with an access token to stdout, and also tries to open it in your browser. If you run it in a container or on a remote machine you will need to suppress this behaviour (with a flag; see `carta --help`) and get the URL and open it yourself.

Please let me know if you run into any issues with the packages or would like more information about setting up the development version. On other platforms you can build it from source -- it's a bit involved, but it's doable. You can avoid building the frontend by installing it from npm or extracting the files from the ubuntu package.

**Comment by o-smirnov** [comment]
Thanks @confluence. I'm still on bionic for now (waiting for KERN-7 to switch...), so please let me know if/when that is supported.

**Comment by confluence** [comment]
Will do -- I should have the packages backported to Bionic soon.

**Comment by o-smirnov** [comment]
BTW, is there a list of package dependencies somewhere for the 18.04 tarballs? I'm trying to run the appimage, but it's a bit of a death by a thousand papercuts, since it keeps asking for various X-related libraries.

**Comment by o-smirnov** [comment]
Nevermind, I see I've already worked this out once: https://github.com/ratt-ru/radiopadre/blob/master/Dockerfile#L27

**Comment by confluence** [comment]
There are now also Bionic packages -- but as of now completely untested!

**Comment by o-smirnov** [comment]
Awesome, thanks, I'll get on that! Is there a tarball version as well?

**Comment by confluence** [comment]
You mean a tarball with the appimage? As far as I know we haven't packaged the development version like that. (I am only managing the Debian packaging.)

**Comment by o-smirnov** [comment]
Yeah, I mean the AppImage (?) version that gets shipped in a tarball, as for the stable release.

I'd like to try the dev version on a shared node, so I don't want to install the .deb for everyone...

Sorry about being so fussy. :)

**Comment by confluence** [comment]
You could install the packages in a Docker container -- that's how I tested the Bionic packages. Then you'd just need to mount your data directory inside the container. The URL printed by the backend should work out of the box.

**Comment by o-smirnov** [comment]
Yep, that indeed is the fallback plan!

**Comment by o-smirnov** [comment]
Hmmm, struggling to get the PPA debs to work on 18.04 (both stable and beta):

```
oms@simon:~$ sudo apt install carta-backend
oms@simon:~$ dpkg -la | grep carta
ii  carta-backend                             1.4.1-1~bionic1                                 amd64        CARTA - Cube Analysis and Rendering Tool for Astronomy
oms@simon:~$ dpkg -S /usr/bin/carta
carta-backend: /usr/bin/carta
oms@simon:~$ /usr/bin/carta --help
carta_backend: symbol lookup error: /usr/lib/x86_64-linux-gnu/libcasa_imageanalysis.so.1: undefined symbol: _ZTVN8casacore10RowNumbersE
oms@simon:~$ dpkg -la | grep libcasa-imageanalysis1
ii  libcasa-imageanalysis1:amd64              3.4.0+5.8.0+2021.2.4-1~bionic1                  amd64        CASA image analysis module
```

Same symbol errors when I install ``carta-beta``.

Tagging @gijzelaer as there may be KERN implications here.

**Comment by gijzelaerr** [comment]
hi! I don't recognise that  `libcasa-imageanalysis1` package (version), I don't think it is part of KERN.

**Comment by confluence** [comment]
@gijzelaer It's not part of KERN; it's part of the custom casacore package in our PPA (which includes this CASA component).

@o-smirnov this is odd; I tested these in a Bionic container. And the package versions look correct to me. Do you have a complete log of the commands you used to install from the PPA?

**Comment by confluence** [comment]
@o-smirnov could you please also paste the output of `dpkg -l | grep casa` ? Do you have any other versions of casa packages instaled in this container?

**Comment by o-smirnov** [comment]
> @gijzelaerr It's not part of KERN; it's part of the custom casacore package in our PPA (which includes this CASA component).

Yeah so that's a conversation I was hoping to start as well. What chances of aligning these with KERN-7 casacore? Otherwise it begins to look a bit scary, mixing KERN and the CARTA PPA...

> @o-smirnov could you please also paste the output of dpkg -l | grep casa ? Do you have any other versions of casa packages instaled in this container?

It's a dev system not a container, so it could have all sorts of odd things installed... I don't have a complete log because I've been installing and reinstalling. But basically:

```
oms@simon:~$ dpkg -l | grep carta
oms@simon:~$ sudo apt install carta-backend
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libcasa-imageanalysis1 libgrpc++1 libgrpc6 libprotobuf17 libpugixml1v5 libzfp0
The following NEW packages will be installed:
  carta-backend libcasa-imageanalysis1 libgrpc++1 libgrpc6 libprotobuf17 libpugixml1v5 libzfp0
0 upgraded, 7 newly installed, 0 to remove and 88 not upgraded.
Need to get 4,682 kB of archives.
After this operation, 20.0 MB of additional disk space will be used.
Do you want to continue? [Y/n] 
Get:1 http://za.archive.ubuntu.com/ubuntu bionic/universe amd64 libpugixml1v5 amd64 1.8.1-7 [82.8 kB]
Get:2 http://ppa.launchpad.net/cartavis-team/carta/ubuntu bionic/main amd64 libcasa-imageanalysis1 amd64 3.4.0+5.8.0+2021.2.4-1~bionic1 [1,465 kB]
Get:3 http://ppa.launchpad.net/cartavis-team/carta/ubuntu bionic/main amd64 libgrpc6 amd64 1.16.1-1ubuntu5~18.04.1 [684 kB]
Get:4 http://ppa.launchpad.net/cartavis-team/carta/ubuntu bionic/main amd64 libprotobuf17 amd64 3.6.1.3-2~18.04.1 [745 kB]
Get:5 http://ppa.launchpad.net/cartavis-team/carta/ubuntu bionic/main amd64 libgrpc++1 amd64 1.16.1-1ubuntu5~18.04.1 [510 kB]
Get:6 http://ppa.launchpad.net/cartavis-team/carta/ubuntu bionic/main amd64 libzfp0 amd64 0.5.5-3~bionic1 [45.8 kB]
Get:7 http://ppa.launchpad.net/cartavis-team/carta/ubuntu bionic/main amd64 carta-backend amd64 1.4.1-1~bionic1 [1,148 kB]         
Fetched 4,682 kB in 8s (609 kB/s)                                                                                                  
Selecting previously unselected package libcasa-imageanalysis1:amd64.
(Reading database ... 326885 files and directories currently installed.)
Preparing to unpack .../0-libcasa-imageanalysis1_3.4.0+5.8.0+2021.2.4-1~bionic1_amd64.deb ...
Unpacking libcasa-imageanalysis1:amd64 (3.4.0+5.8.0+2021.2.4-1~bionic1) ...
Selecting previously unselected package libgrpc6:amd64.
Preparing to unpack .../1-libgrpc6_1.16.1-1ubuntu5~18.04.1_amd64.deb ...
Unpacking libgrpc6:amd64 (1.16.1-1ubuntu5~18.04.1) ...
Selecting previously unselected package libprotobuf17:amd64.
Preparing to unpack .../2-libprotobuf17_3.6.1.3-2~18.04.1_amd64.deb ...
Unpacking libprotobuf17:amd64 (3.6.1.3-2~18.04.1) ...
Selecting previously unselected package libgrpc++1:amd64.
Preparing to unpack .../3-libgrpc++1_1.16.1-1ubuntu5~18.04.1_amd64.deb ...
Unpacking libgrpc++1:amd64 (1.16.1-1ubuntu5~18.04.1) ...
Selecting previously unselected package libpugixml1v5:amd64.
Preparing to unpack .../4-libpugixml1v5_1.8.1-7_amd64.deb ...
Unpacking libpugixml1v5:amd64 (1.8.1-7) ...
Selecting previously unselected package libzfp0.
Preparing to unpack .../5-libzfp0_0.5.5-3~bionic1_amd64.deb ...
Unpacking libzfp0 (0.5.5-3~bionic1) ...
Selecting previously unselected package carta-backend.
Preparing to unpack .../6-carta-backend_1.4.1-1~bionic1_amd64.deb ...
Unpacking carta-backend (1.4.1-1~bionic1) ...
Setting up libpugixml1v5:amd64 (1.8.1-7) ...
Setting up libprotobuf17:amd64 (3.6.1.3-2~18.04.1) ...
Setting up libcasa-imageanalysis1:amd64 (3.4.0+5.8.0+2021.2.4-1~bionic1) ...
Setting up libzfp0 (0.5.5-3~bionic1) ...
Setting up libgrpc6:amd64 (1.16.1-1ubuntu5~18.04.1) ...
Setting up libgrpc++1:amd64 (1.16.1-1ubuntu5~18.04.1) ...
Setting up carta-backend (1.4.1-1~bionic1) ...
Processing triggers for libc-bin (2.27-3ubuntu1.3) ...
oms@simon:~$ /usr/bin/carta
carta_backend: symbol lookup error: /usr/lib/x86_64-linux-gnu/libcasa_imageanalysis.so.1: undefined symbol: _ZTVN8casacore10RowNumbersE
oms@simon:~$ dpkg -S /usr/lib/x86_64-linux-gnu/libcasa_imageanalysis.so.1
libcasa-imageanalysis1:amd64: /usr/lib/x86_64-linux-gnu/libcasa_imageanalysis.so.1
oms@simon:~$ 
oms@simon:~$ dpkg -la | grep casa
ii  casacore-data                             20201201-160001-2                               all          Casacore data files
ii  casacore-dev:amd64                        3.3.0-1kern1                                    amd64        CASA core library development files
ii  casacore-tools                            3.3.0-1kern1                                    amd64        Tools built with CASA
ii  casalite                                  5.6.0-1                                         amd64        Common Astronomy Software Application
ii  casarest                                  1.7.0-1kern1                                    amd64        standalone radio interferometric imager derived from CASA
ii  libcasa-casa2:amd64                       2.4.1-1                                         amd64        CASA core modules
ii  libcasa-casa5:amd64                       3.3.0-1kern1                                    amd64        CASA core modules
ii  libcasa-coordinates5:amd64                3.3.0-1kern1                                    amd64        CASA coordinates library
ii  libcasa-derivedmscal5:amd64               3.3.0-1kern1                                    amd64        CASA derived mscal library
ii  libcasa-fits5:amd64                       3.3.0-1kern1                                    amd64        CASA FITS library
ii  libcasa-imageanalysis1:amd64              3.4.0+5.8.0+2021.2.4-1~bionic1                  amd64        CASA image analysis module
ii  libcasa-images5:amd64                     3.3.0-1kern1                                    amd64        CASA image processing library
ii  libcasa-lattices5:amd64                   3.3.0-1kern1                                    amd64        CASA lattice library
ii  libcasa-meas5:amd64                       3.3.0-1kern1                                    amd64        CASA functions handling measures
ii  libcasa-measures2:amd64                   2.4.1-1                                         amd64        CASA measures library
ii  libcasa-measures5:amd64                   3.3.0-1kern1                                    amd64        CASA measures library
ii  libcasa-mirlib5:amd64                     3.3.0-1kern1                                    amd64        CASA mirlib library
ii  libcasa-ms2:amd64                         2.4.1-1                                         amd64        CASA MeasurementSet library
ii  libcasa-ms5:amd64                         3.3.0-1kern1                                    amd64        CASA MeasurementSet library
ii  libcasa-msfits5:amd64                     3.3.0-1kern1                                    amd64        CASA msfits library
ii  libcasa-python3-5:amd64                   3.3.0-1kern1                                    amd64        CASA Python bindings
ii  libcasa-python5:amd64                     3.3.0-1kern1                                    amd64        CASA legacy Python 2 bindings
ii  libcasa-scimath-f2:amd64                  2.4.1-1                                         amd64        CASA scimath F library
ii  libcasa-scimath-f5:amd64                  3.3.0-1kern1                                    amd64        CASA scimath F library
ii  libcasa-scimath2:amd64                    2.4.1-1                                         amd64        CASA basic mathematical modules
ii  libcasa-scimath5:amd64                    3.3.0-1kern1                                    amd64        CASA basic mathematical modules
ii  libcasa-tables2:amd64                     2.4.1-1                                         amd64        CASA table system
ii  libcasa-tables5:amd64                     3.3.0-1kern1                                    amd64        CASA table system
ii  python-casacore                           3.3.1-1kern1                                    amd64        Python 2 bindings to the casacore library
ii  python3-casacore                          3.3.1-1kern1                                    amd64        Python 3 bindings to the casacore library
oms@simon:~$

**Comment by o-smirnov** [comment]
So when you do a fresh install into a container, you're probably pulling your own casacore etc. from your PPA.

I'm installing on top of a KERN-6-basded system, and the casacore dependencies are satisfied by my existing packages. So I guess:

* your package dependencies may need to be made more specific as to force the use of your own casacore

* it probably won't work on top of a KERN-6 install, which is a worry, see above...

**Comment by confluence** [comment]
(The reason I thought the dependencies were fine is that they're fine in the *focal* package -- but the ones in the bionic package have no versions. This may be because an older version of debhelper was used to build it. I will figure out how to fix the package.)

**Comment by gijzelaerr** [comment]
I'm quite impressed that you managed to package up CASA6 and CARTA into separate packages. Well done. I've tried this before and just gave up at some point due to multiple reasons. The most important reason is that it is just a lot of work to keep up with the CASA releases and keep on fixing the issues. Also, the dependency on modified and unreleased casacore is a massive issue. 

We eventually chose a bit more programmatic approach, just put the big binary monolith into a Debian package and add the symlinks. This way, we don't interfere with software depending on the KERN casacore libs, but also it just saves a lot of time in reverse-engineering the CASA6 installation procedure. We decided this would be the only sensible way forward unless the CASA developers would synchronise their releases with the casacore releases and make their build system less fragile.

I didn't look at this for a while now, so that the situation might have changed. What is your main motivation to split CASA into multiple packages, and what is your long-term plan in maintaining these?

**Comment by gijzelaerr** [comment]
> (The reason I thought the dependencies were fine is that they're fine in the _focal_ package -- but the ones in the bionic package have no versions. This may be because an older version of debhelper was used to build it. I will figure out how to fix the package.)

I don't understand what you are saying here. I'm not saying your wrong; I don't understand what you are saying :) If you are uploading a casacore to your PPA with the same SO numbers as our casacore but with mismatching ABIs, the packages will be conflicting and will cause issues. This is going to be an issue for people enabling both this CARTA ppa and the KERN ppa. This can happen quite quickly; users/astronomers are not always completely aware of what they are doing when following installation instructions. This might result in quite some issues on our issue trackers with vaguely described issues and bugs.

**Comment by confluence** [comment]
The version of CARTA in your package is the standalone Electron app version. These packages are specifically intended to make it possible to install the different components of CARTA independently, which is why they're structured like this.

We're not building all of CASA6; we have a very pared-down CMake configuration which builds just this one CASA module and the specific version of casacore that it needs. We were previously building a single binary package for our "carta-casacore" version, but it was still installing the same libraries to standard locations (although they had different SO numbers). I tried to make the new packages more consistent with the way that existing casacore packages were being built, and updated the SO numbers because they had gone out of sync with the casacore version.

My original intention was for the PPA casacore packages to supersede the KERN packages on a system where both PPAs are enabled, since the casacore version is newer -- but I realise that this may not be an ideal solution if other applications require the specific KERN version, and that these changes have made it impossible for the packages to coexist. I was hoping that eventually it would be possible for us to build just the CASA package against a more standard version of casacore, but that may be much more complicated to arrange than I thought.

We don't want to return to a monolithic casacore package, because we want to be able to install just the binaries without headers, etc.. But we could perhaps name and split the packages differently, and use different SO numbers (there's a simple way to do this using CASA's custom build suffix), to create a parallel casacore install which doesn't interfere with the "normal" version of casacore. I'm going to test out some options.

(My comment about the dependencies in the backend package was specifically about the backend dependencies lacking the correct minimum versions. If they were correct, the backend package would have required the custom versions to be installed from the PPA. This doesn't solve the underlying problem, but it is a bug in the packaging.)

**Comment by confluence** [comment]
An existing build option in CASA is to use a long timestamped version number for the built libraries, and I think that is probably the way for us to go. My general plan is to create one `carta-casacore` package with the libraries, and one `carta-casacore-dev` package with the headers (this would only be used by our developers). I can't see a way around having the `carta-casacore-dev` package clash with the `casacore-dev` package (unless we completely change the include paths everywhere), but this is a much smaller problem, since our header package would have a very limited audience.

If we can sort this problem out, it may make sense for KERN to include the release versions of the CARTA packages and their binary dependencies in future (and our custom file format converter). But this should probably wait until after the 2.0 release, which is going to be the first version which can be run easily from the components in a standalone way.

**Comment by gijzelaerr** [comment]
The header files can be installed in a non-default search path prefix, which can be set compile time by the limited audience :) So in the end it does sound like we could make this work. A hacky way, but better a pragmatic hacky way than no way.

Great that you are open to inclusion into KERN.

**Comment by confluence** [comment]
I am moving this discussion to a [more on-topic place](https://github.com/idia-astro/carta-casacore-deb/issues/1). :)

**Comment by confluence** [comment]
@o-smirnov FYI, I have fixed the packaging bug -- this doesn't change the current situation with a set of custom incompatible casacore packages being required (I have filed an issue for that in the package's repo, linked above), but these dependencies are now accurately reflected in the package metadata and it should no longer be possible to end up with a broken install.

**Comment by o-smirnov** [comment]
Yes, thank you, I am not gleefully using this!

**Comment by o-smirnov** [comment]
Oops, I mean **now** gleefuly using....
