### ISSUE TITLE
Label ellipse region axes as semi-major/minor/radius

### ISSUE THREAD

**Issue by Jordatious** [CARTAvis/carta#70]
The axes for ellipse regions seem to be the semi-major/minor axis (or radius for circles), not diameter, but this isn't displayed anywhere.

**Comment by kswang1029** [comment]
Would it work better if we show "Semi-axes" instead of the current "Axes"?

![Screen Shot 2021-03-24 at 9 26 27 AM](https://user-images.githubusercontent.com/20819712/112240306-0ce6f880-8c83-11eb-8e4f-6fce199d4b97.png)
