### ISSUE TITLE
Show colorbar on image view

### ISSUE THREAD

**Issue by elnjensen** [CARTAvis/carta#73]
It would be nice to be able to see what colors map to what values when viewing an image.  Maybe there's a way to do this, but searching the docs for "colorbar" doesn't yield anything.

**Comment by veggiesaurus** [comment]
Implemented in https://github.com/CARTAvis/carta-frontend/pull/1366, will be available in the upcoming release (2.0). Screenshot from current `dev` build:

![spire500_ext fits-image-2021-04-01-18-15-19](https://user-images.githubusercontent.com/592504/113336662-06ade780-9327-11eb-9644-c4a721567cd7.png)

**Comment by elnjensen** [comment]
Thanks!  I searched issues in this repo before asking, but didn't realize there was a separate frontend repo.
