### ISSUE TITLE
Question: Where can I find a list of debug commands?

### ISSUE THREAD

**Issue by keflavich** [CARTAvis/carta#78]
I find commands like `appendFile` and `openFile` necessary for comparing reasonable numbers (~5-20) of images. Are there other commands for, e.g., loading region files?  Is there a list of the available debug commands?

**Comment by veggiesaurus** [comment]
unfortunately there isn't a very concise list, although possibly @confluence could put together something for you. Those commands are `@action` functions in the `AppStore` source file. For example, here's [`appendFile`](https://github.com/CARTAvis/carta-frontend/blob/71a0997a68e36bb197f0c478405bfad44f03c7a2/src/stores/AppStore.ts#L520). For now, you might want to just have a search through that file for the `@action` commands.

You can also access `@action` functions on a specific image. For example: `activeFrame.setZoom(2)` uses [this](https://github.com/CARTAvis/carta-frontend/blob/71a0997a68e36bb197f0c478405bfad44f03c7a2/src/stores/FrameStore.ts#L1478) `@action`.

**Comment by veggiesaurus** [comment]
I'm going to turn this into an issue for generating documentation from our source code :+1:

**Comment by veggiesaurus** [comment]
closed in favour of https://github.com/CARTAvis/carta-frontend/issues/1482.
