### ISSUE TITLE
Feature request - RESTful API to control the front end

### ISSUE THREAD

**Issue by robertoabraham** [CARTAvis/carta#81]
My apologies if my requested feature already exists (and I suspect it does), but I've been unable to find documentation on a RESTful API to control the front end from a web browser.

I can think  of all sorts of things I'd love to be able to do by controlling CARTA using a RESTful API, but just for the moment I really only want to do something really simple. I'd like to be able to send a link to an image so members of my team can view an image being managed by a remote CARTA server (running in site deployment mode) without having to drill through a folder hierarchy. In other words, if the CARTA server is running on `123.456.789.123` and I want to direct a remote team member to an image `myimage.fits` that lives in a directory `/foo/bar` I'd like to be able to direct them to something like this link and when they click on it the CARTA front end would display the image in their browser:

https://123.456.789.123/&folder=foo/bar/&file=myimage.fits

For bonus points I'd also like to set the color table and the display data range in the URI, but I'd be happy if I could just get an image to open. 

I suspect what I'd like to do might already be possible, based on discussion of Issue https://github.com/CARTAvis/carta/issues/68 but I've tried the syntax noted in that issue and it doesn't seem to work. I suspect I just need a pointer to some documentation on the API.  

Thanks in advance for any help you can offer!

**Comment by veggiesaurus** [comment]
@robertoabraham the following should work:

https://123.456.789.123/?file=/foo/bar/myimage.fits

URL query parameters are started with a `?` and separated by a `&`. If you have unsupported characters in your file or folder name, you'll need to [encode](https://www.w3schools.com/tags/ref_urlencode.ASP) those characters when putting them into the URL. 

As for a RESTful API, we are currently working on the following:
1. Python scripting interface for controlling most of CARTA's functionality
2. Lower-level Javascript scripting interface (mostly for power users to save and run snippets of code)
3. "Project / Workspace" files that you could save and load. This would allow you to save your current CARTA setup to file and load at a later stage. This will also be supported with a URL query parameter.

**Comment by robertoabraham** [comment]
Thanks @veggiesaurus that is super helpful and I'll mark the issue as closed. 

The planned feature set for the API looks amazing... absolutely perfect for my team's needs. CARTA is proving to be a real game changer for my team!
