### ISSUE TITLE
Feature request: open multiple files via the command line

### ISSUE THREAD

**Issue by IanHeywood** [CARTAvis/carta#84]
It would be useful to be able to open mulitple files via the command line, ideally with wildcard support. The current behaviour is:

```
$ carta 1*/*MTP*pcalmask-MFS-image.fits
Error: Requested file or directory does not exist, or image is a non standard type. Please check.
```

and when many files are spread across multiple paths loading them all individually via the GUI is tedious. 

Thanks.

**Comment by kswang1029** [comment]
Would it be acceptable if your request is achieved via the scripting interface which is currently under development? That is, you write a short script and specify explicitly the image paths to load?

**Comment by IanHeywood** [comment]
That sounds like it would be fine. Support for a list is also fine, as I can use glob or similar to resolve a string with a wildcard in it into a list of files and pass that to the carta exectuable. I think being able to use `*` is key.

Thanks @kswang1029

**Comment by kswang1029** [comment]
Thanks for the feature request. We will have some internal discussions.

**Comment by veggiesaurus** [comment]
@IanHeywood thanks for the suggestion. We were planning on implementing this at some stage, and it was already partially complete. Here's the [pull request](https://github.com/CARTAvis/carta-backend/pull/915) if you're interested. Should be ready for the next beta release in October (3.0-beta.2).

Proposed usage would just be `carta *.fits` or whatever other combination of paths you want.
