### ISSUE TITLE
Bug in beta: The coordinates are read incorrectly

### ISSUE THREAD

**Issue by spectram** [CARTAvis/carta#86]
Attaching the extracted png and header file information of the input file (decam g band image). Issue specific to this release, previous versions parsed the same file correctly. 

![decam_g_tile22 fits-image-2021-09-04-14-46-50](https://user-images.githubusercontent.com/83280431/132095125-9264d77a-cc92-4105-940f-6c4bca18e546.png)
[decam_g_tile22.fits-Header.txt](https://github.com/CARTAvis/carta/files/7109787/decam_g_tile22.fits-Header.txt)

**Comment by veggiesaurus** [comment]
@spectram I'm wondering if there is a problem with how the header is actually being reported to the CARTA frontend. Would you be able to attach the raw header (from something like `fitshdr` or `fitsheader`)?

**Comment by spectram** [comment]
> @spectram I'm wondering if there is a problem with how the header is actually being reported to the CARTA frontend. Would you be able to attach the raw header (from something like `fitshdr` or `fitsheader`)?

@veggiesaurus please find attached
[decamhdr.txt](https://github.com/CARTAvis/carta/files/7116597/decamhdr.txt)

**Comment by kswang1029** [comment]
I found something odd based on the two fits headers:
with decam_g_tile22.fits-Header.txt (header via CARTA), 

> CTYPE1 = DEC--TAN /  WCS projection type for this axis
CTYPE2 = RA---TAN /  WCS projection type for this axis

but with decamhdr.txt (via fitshdr or fitsheader or else):
> CTYPE2  = 'DEC--TAN'           / WCS projection type for this axis              
CTYPE1  = 'RA---TAN'           / WCS projection type for this axis   

This might be the reason why the rendered grid in CARTA is odd.

**Comment by kswang1029** [comment]
@spectram could you confirm that the correct grid should be something like the following? thanks.
![file-1](https://user-images.githubusercontent.com/20819712/133051863-e80804a8-f118-470d-8da0-e0a6259e486a.png)

**Comment by kswang1029** [comment]
@spectram is it possible to get a copy of your image for debugging and bug fix? A small subimage is fine. We would like to see why via CARTA CTYPE1 and CTYPE2 are swapped. 

If it is not convenient that's fine. We will try to make a fake one based on the FITS header you provided. 

thank you again.

**Comment by spectram** [comment]
> @spectram is it possible to get a copy of your image for debugging and bug fix? A small subimage is fine. We would like to see why via CARTA CTYPE1 and CTYPE2 are swapped.
> 
> If it is not convenient that's fine. We will try to make a fake one based on the FITS header you provided.
> 
> thank you again.

Hi @kswang1029 The grid looks correct to me. Please find a small subcube. Do let me know if this is sufficient. I can also extract a bigger one if required. Although, I think this opened correctly for me.
[subcube.zip](https://github.com/CARTAvis/carta/files/7187239/subcube.zip)

**Comment by kswang1029** [comment]
@spectram do you think this is still an issue with v3-beta2 release? Following is a screenshot of the subcube example image loaded in v3-beta2. It seems fine. 
![subcube.fits-image-2022-03-17-11-23-43.png](https://images.zenhubusercontent.com/590bdf9f51aa2c30577d5260/f547c0a0-80c1-4dab-8f6e-cd8cd7532ddb)

**Comment by spectram** [comment]
@kswang1029 The issue has been fixed. Sorry for the delay in confirmation.
