### ISSUE TITLE
Directory labelled as empty for too long

### ISSUE THREAD

**Issue by Jordatious** [CARTAvis/carta#88]
This is related to https://github.com/CARTAvis/carta/issues/87 but it technically a different issue.

Like many CARTA users, the directory that opens by default when CARTA is launched contains many images, so the file browser takes a long time to generate the list, and in the mean-time, labels the directory as empty. After perhaps 5 seconds, a loading bar pops up and one can cancel the loading and browse to a different directory of choice.

Discussing this with @veggiesaurus, we need a better non-ideal state. We don't want the loading bar to come up for a short read, but we also don't want it to hang for so long. We discussed a 1-2 second delay for the loading bar would be much better. I'd vote for 1 second!

**Comment by kswang1029** [comment]
The 5s delay was intentionally implemented. Switching to 1 or 2s is fine as long as there is no flash effect happening. I seem to remember we had such issue if the delay is too short when @TienHao was implementing this feature

**Comment by Jordatious** [comment]
Ok thanks. I would imagine it's a function of environment / filesystem, so perhaps it could be set as a variable during the build? I would be happy to test this for IDIA. I think 1-2 seconds would work fine there.

**Comment by kswang1029** [comment]
> Ok thanks. I would imagine it's a function of environment / filesystem, so perhaps it could be set as a variable during the build? I would be happy to test this for IDIA. I think 1-2 seconds would work fine there.

It is part of the codebase.

**Comment by veggiesaurus** [comment]
what if we switch to a non-ideal state ("loading files" with a spinner) after 500 ms and then show the loading screen after 5 seconds?

**Comment by kswang1029** [comment]
> what if we switch to a non-ideal state ("loading files" with a spinner) after 500 ms and then show the loading screen after 5 seconds?

Ideal solution 🙂

**Comment by Jordatious** [comment]
That could work! Although I'd imagine people like me would still get impatient waiting, so having a way to cancel quickly, or show all files, as discussed in https://github.com/CARTAvis/carta/issues/87, would be much more ideal!

**Comment by Jordatious** [comment]
Again, I'd like to emphasise how good CARTA is as a fast visualisation tool of big data, and that these "waiting features" are in the opposite direction!

**Comment by kswang1029** [comment]
> Again, I'd like to emphasise how good CARTA is as a fast visualisation tool of big data, and that these "waiting features" are in the opposite direction!

We are probably hitting the performance limit of the pre-parsing-image-type step (we had a backend issue before to address this). The alternative (faster) should be showing all files and folders without this step.

**Comment by veggiesaurus** [comment]
@Jordatious @kswang1029 Does this look ok? It uses a unified approach for all non-ideal states in the dialog (progress spinner instead of the task alert while list is loading), and displays it as an overlay on top of the table. I'm not entirely sure the blur backdrop filter is required :thinking: 

https://user-images.githubusercontent.com/592504/133779289-77e2dc6f-b01c-44b7-840d-f2225b4de199.mp4

**Comment by Jordatious** [comment]
Looks great! I'm still quite keen for a more general solution to https://github.com/CARTAvis/carta/issues/87, but for this related but different issue, this seems like a good solution.
