### ISSUE TITLE
Poor performance when many regions loaded

### ISSUE THREAD

**Issue by Jordatious** [CARTAvis/carta#90]
One awkward thing about CARTA (a fast visualisation tool for big data) is how it doesn't handle many regions. A standard workflow would include overlaying a ds9 region file output from a source finder like PyBDSF or Aegean, which could include hundreds or thousands of regions, which CARTA cannot handle. I believe I've seen CARTA either crash or freeze for such cases. Although the catalogue tool could handle this, it does not replicate the region files that show the exact shape of the fitted sources. 

It may be worth considering limiting the region functionality above some threshold of a large number of regions (10? - assuming that's the limiting factor). As a user, I don't need all the specific region functionality when I have 100 of them loaded. And to remove all the regions loaded, one does not want to go through and manually remove every single one. 

ds9 can handle this and also enables selecting all regions to remove or change colour, etc. Perhaps CARTA could go beyond this by putting regions within groups that can be labelled? A simple shift- / control-click to select multiple and group them would work.

My apologies if this is an issue already submitted, or if it should really be two issues!

**Comment by veggiesaurus** [comment]
@duidae is currently working on region performance. Hopefully we will have some improvements with beta-2. I'd  like to support thousands of regions in theory. However, this will make handling things like the region dropdowns a bit of a nightmare!

**Comment by Jordatious** [comment]
Ok great! I agree, thousands would be great, and I think some of the ways you address these large numbers for contours and catalogues could also work here.

>  this will make handling things like the region dropdowns a bit of a nightmare!

Exactly. Hence my suggestion to disable some of the region functionality when the count is above some number. Or even better, enable some of the functionality for groups of regions.

**Comment by duidae** [comment]
hi @Jordatious, thank you for your helpful feedback and we are now working on it to optimize the freeze & performance issue, and will keep you updated when any improvement is added into the new release.

**Comment by Jordatious** [comment]
Is there a way I can test this for my own data?

**Comment by veggiesaurus** [comment]
> ds9 can handle this and also enables selecting all regions to remove or change colour, etc. Perhaps CARTA could go beyond this by putting regions within groups that can be labelled? A simple shift- / control-click to select multiple and group them would work.

@Jordatious can you create a separate issue for this, if it doesn't already exist?

**Comment by duidae** [comment]
> Is there a way I can test this for my own data?

hi @Jordatious, some related improvements will be included in the next beta release, please have a try when the package is ready and the date would be around the end of November this year. Stay tuned to CARTA & hope you enjoy it!

**Comment by veggiesaurus** [comment]
the rendering performance has now been improved, but we still need to improve the region list widget (see https://github.com/CARTAvis/carta-frontend/issues/1694)

**Comment by Jordatious** [comment]
> > ds9 can handle this and also enables selecting all regions to remove or change colour, etc. Perhaps CARTA could go beyond this by putting regions within groups that can be labelled? A simple shift- / control-click to select multiple and group them would work.
> 
> @Jordatious can you create a separate issue for this, if it doesn't already exist?

[Done](https://github.com/CARTAvis/carta/issues/100)

**Comment by Jordatious** [comment]
Thanks for working on this! I've just tested this on the updated IDIA beta server, using a 5x5k image and overlaying the PyBDSF source catalogue, which contains ~8.5k regions. I first did this with the region list widget open, and it loaded very slowly (~1 minute - I timed it!), and when I tried to pan and zoom, etc, it was very slow performance, until it basically grinded to a halt, with Chrome saying the page was unresponsive! I then tried it again with the region list widget closed, and it was better performance, but still took 40 seconds to load, and had slow performance. I think the feature requested in #100 would address many of these issues.

**Comment by kswang1029** [comment]
> Thanks for working on this! I've just tested this on the updated IDIA beta server, using a 5x5k image and overlaying the PyBDSF source catalogue, which contains ~8.5k regions. I first did this with the region list widget open, and it loaded very slowly (~1 minute - I timed it!), and when I tried to pan and zoom, etc, it was very slow performance, until it basically grinded to a halt, with Chrome saying the page was unresponsive! I then tried it again with the region list widget closed, and it was better performance, but still took 40 seconds to load, and had slow performance. I think the feature requested in #100 would address many of these issues.

partly this is because the region list table has not been virtualized yet so it renders lots of non-visible rows.

**Comment by veggiesaurus** [comment]
moving to `In Progress` again based on @Jordatious's comments. I do think we need to draw the line somewhere though in terms of the number of interactive regions supported. My feeling is that 10k+ regions should be a catalogue, rather than an interactive set of regions
