### ISSUE TITLE
Integer values in catalogue are not displayed

### ISSUE THREAD

**Issue by lh-astro** [CARTAvis/carta#93]
Integer values in fits catalogues are displayed empty in CARTA's catalogue feature.

Tested on carta-beta.idia.ac.za

Screenshot: https://transfer.sh/RpFPwk/screenshot1.jpg
(sorry, github image upload error still persists.)

**Comment by veggiesaurus** [comment]
are these 64-bit integers? Duplicate of https://github.com/cartavis/carta/issues/85?

**Comment by lh-astro** [comment]
Yes, it is int64. Probably duplicate.
