### ISSUE TITLE
Feature Request: Setting S > N as 0 degree for line region PA

### ISSUE THREAD

**Issue by spectram** [CARTAvis/carta#95]
I use [pvextractor](https://pvextractor.readthedocs.io/en/latest/programmatic.html) from Astropy for producing slices but "the position angle is defined counter-clockwise from North, and the direction of the path is such that for a position angle of zero, the path is defined from South to North." This is consistent with slit positioning definitions (on sky PA) for long slit observations. 

If this is not possible then, I recommend cautioning the user of the 90 degree phase shift in definitions.

**Comment by kswang1029** [comment]
Thanks for the suggestion. We have already fixed the PA of the line region definition. It will be part of the v3-beta2 release.

**Comment by spectram** [comment]
@kswang1029 - Slightly unrelated: When I import regions that were exported from CARTA in the past, they are considerably offset. I couldn't see any reported issues regarding this. Shall I create one?

**Comment by kswang1029** [comment]
> @kswang1029 - Slightly unrelated: When I import regions that were exported from CARTA in the past, they are considerably offset. I couldn't see any reported issues regarding this. Shall I create one?

Yes please. Thank you.

**Comment by kswang1029** [comment]
should have been addressed.
