### ISSUE TITLE
Bug: Failure to load images, fast load of spectra

### ISSUE THREAD

**Issue by keflavich** [CARTAvis/carta#96]
I've been encountering frequent issues when loading FITS data in which the image frames never load, but any spectra I extract are loaded and displayed rapidly, even when I do fairly large region averages.  The "streaming images" cloud tile says there are 9 images loading, but they never show up.  

This issue has only affected some data sets I've been working on recently that I acquired from a colleague.  My initial assumption was that they were something to do with FITS data with varying resolution per channel, so I convolved them to a common resolution and wrote them back as a fixed beam, but the issue persists.

This is on CARTA v2.0.

**Comment by keflavich** [comment]
I do see some warnings in the log:
```
2021-09-29 14:26:49     WARN            File /orange/adamginsburg/salt/sanhueza/W33A/W33A.config8.spw0.robust0.5.image_cb_small.fits Physical record 2 logical record 10 --
2021-09-29 14:26:49     WARN    +               [FitsInput::read_header_rec()] Misplaced prima
```

**Comment by kswang1029** [comment]
With the same image, are you able to reproduce the issue with v3b1?

**Comment by keflavich** [comment]
I can't run v3b1; see https://github.com/CARTAvis/carta-frontend/issues/1661 (sorry I posted on the wrong repo)

**Comment by kswang1029** [comment]
> I can't run v3b1; see [CARTAvis/carta-frontend#1661](https://github.com/CARTAvis/carta-frontend/issues/1661) (sorry I posted on the wrong repo)

Hmm right🙈 could you provide an example fits header? (Extract from ds9, not carta)

**Comment by kswang1029** [comment]
Do you see any error message from the browser console? Something like
![28B22BCF-C422-4E8C-BE79-DCEBF42A095F](https://user-images.githubusercontent.com/20819712/135292208-6d1c612c-efa4-42a3-b70a-74ff251bcb63.jpeg)

**Comment by keflavich** [comment]
yep:
![image](https://user-images.githubusercontent.com/143715/135292696-648ebc93-d77d-4eea-92cd-36874b38913d.png)

**Comment by keflavich** [comment]
header:
```
$ imhead W33A.config8.spw0.robust0.5.image_cb_small.fits
SIMPLE  =                    T / conforms to FITS standard
BITPIX  =                  -64 / array data type
NAXIS   =                    3 / number of array dimensions
NAXIS1  =                  513
NAXIS2  =                  513
NAXIS3  =                 1931
BTYPE   = 'Intensity'
OBJECT  = 'W33A    '
BUNIT   = 'beam-1 Jy'          / Brightness (pixel) unit
ALTRVAL =   1.198699545164E+06 /Alternate frequency reference value
ALTRPIX =   1.000000000000E+00 /Alternate frequency reference pixel
VELREF  =                  257 /1 LSR, 2 HEL, 3 OBS, +256 Radio
COMMENT casacore non-standard usage: 4 LSD, 5 GEO, 6 SOU, 7 GAL
TELESCOP= 'ALMA    '
OBSERVER= 'psanhueza'
OBSRA   =   2.736641595834E+02
OBSDEC  =  -1.786695000001E+01
INSTRUME= 'ALMA    '
DISTANCE=   0.000000000000E+00
MPIPROCS=                   11
CHNCHNKS=                   34
MEMREQ  =        2.6883141E+04
MEMAVAIL=        7.9343604E+02
USEWEIGH=                    F
DATE    = '2021-09-28T04:05:36.779434' /Date FITS file was written
ORIGIN  = 'CASA 6.3.0-48 CASAtools:v1.0.0'
CASAMBM =                    T /CASA multiple BEAMS table present
BMAJ    = 2.68598459661006E-05
BMIN    = 1.81552912626001E-05
BPA     =   -83.22697448730469
WCSAXES =                    3 / Number of coordinate axes
CRPIX1  =                257.0 / Pixel coordinate of reference point
CRPIX2  =                257.0 / Pixel coordinate of reference point
CRPIX3  =                  1.0 / Pixel coordinate of reference point
CDELT1  =  -2.777777777778E-06 / [deg] Coordinate increment at reference point
CDELT2  =   2.777777777778E-06 / [deg] Coordinate increment at reference point
CDELT3  =       976612.5704956 / [Hz] Coordinate increment at reference point
CUNIT1  = 'deg'                / Units of coordinate increment and value
CUNIT2  = 'deg'                / Units of coordinate increment and value
CUNIT3  = 'Hz'                 / Units of coordinate increment and value
CTYPE1  = 'RA---SIN'           / Right ascension, orthographic/synthesis project
CTYPE2  = 'DEC--SIN'           / Declination, orthographic/synthesis projection
CTYPE3  = 'FREQ'               / Frequency (linear)
CRVAL1  =       273.6641595834 / [deg] Coordinate value at reference point
CRVAL2  =      -17.86695000001 / [deg] Coordinate value at reference point
CRVAL3  =       233562367862.0 / [Hz] Coordinate value at reference point
PV2_1   =                  0.0 / SIN projection parameter
PV2_2   =                  0.0 / SIN projection parameter
LONPOLE =                180.0 / [deg] Native longitude of celestial pole
LATPOLE =      -17.86695000001 / [deg] Native latitude of celestial pole
RESTFRQ =       234500000000.0 / [Hz] Line rest frequency
MJDREF  =                  0.0 / [d] MJD of fiducial time
DATE-OBS= '2017-09-11T01:47:10.440000' / ISO-8601 time of observation
MJD-OBS =      58007.074426389 / [d] MJD of observation
OBSGEO-X=       2225142.180269 / [m] observatory X-coordinate
OBSGEO-Y=      -5440307.370349 / [m] observatory Y-coordinate
OBSGEO-Z=      -2481029.851874 / [m] observatory Z-coordinate
RADESYS = 'ICRS'               / Equatorial coordinate system
SPECSYS = 'LSRK'               / Reference frame of spectral coordinates
HISTORY CASA START LOGTABLE
...snip...
HISTORY CASA END LOGTABLE
HISTORY Written by spectral_cube v0.5.1.dev194+g3ec43af on 2021/09/29-08:46:43
END
```

(the problem exists with the original CASA version too)

**Comment by kswang1029** [comment]
I think it might be due to some tiles are 256x1. We have fixed this issue https://github.com/CARTAvis/carta-frontend/issues/1365

I need to check the fix is in v3b1 or our latest dev.

I guess if you crop the image to 512x512 it will work with v2.0

**Comment by kswang1029** [comment]
> header:
> 
> ```
> $ imhead W33A.config8.spw0.robust0.5.image_cb_small.fits
> SIMPLE  =                    T / conforms to FITS standard
> BITPIX  =                  -64 / array data type
> NAXIS   =                    3 / number of array dimensions
> NAXIS1  =                  513
> NAXIS2  =                  513
> NAXIS3  =                 1931
> BTYPE   = 'Intensity'
> OBJECT  = 'W33A    '
> BUNIT   = 'beam-1 Jy'          / Brightness (pixel) unit
> ALTRVAL =   1.198699545164E+06 /Alternate frequency reference value
> ALTRPIX =   1.000000000000E+00 /Alternate frequency reference pixel
> VELREF  =                  257 /1 LSR, 2 HEL, 3 OBS, +256 Radio
> COMMENT casacore non-standard usage: 4 LSD, 5 GEO, 6 SOU, 7 GAL
> TELESCOP= 'ALMA    '
> OBSERVER= 'psanhueza'
> OBSRA   =   2.736641595834E+02
> OBSDEC  =  -1.786695000001E+01
> INSTRUME= 'ALMA    '
> DISTANCE=   0.000000000000E+00
> MPIPROCS=                   11
> CHNCHNKS=                   34
> MEMREQ  =        2.6883141E+04
> MEMAVAIL=        7.9343604E+02
> USEWEIGH=                    F
> DATE    = '2021-09-28T04:05:36.779434' /Date FITS file was written
> ORIGIN  = 'CASA 6.3.0-48 CASAtools:v1.0.0'
> CASAMBM =                    T /CASA multiple BEAMS table present
> BMAJ    = 2.68598459661006E-05
> BMIN    = 1.81552912626001E-05
> BPA     =   -83.22697448730469
> WCSAXES =                    3 / Number of coordinate axes
> CRPIX1  =                257.0 / Pixel coordinate of reference point
> CRPIX2  =                257.0 / Pixel coordinate of reference point
> CRPIX3  =                  1.0 / Pixel coordinate of reference point
> CDELT1  =  -2.777777777778E-06 / [deg] Coordinate increment at reference point
> CDELT2  =   2.777777777778E-06 / [deg] Coordinate increment at reference point
> CDELT3  =       976612.5704956 / [Hz] Coordinate increment at reference point
> CUNIT1  = 'deg'                / Units of coordinate increment and value
> CUNIT2  = 'deg'                / Units of coordinate increment and value
> CUNIT3  = 'Hz'                 / Units of coordinate increment and value
> CTYPE1  = 'RA---SIN'           / Right ascension, orthographic/synthesis project
> CTYPE2  = 'DEC--SIN'           / Declination, orthographic/synthesis projection
> CTYPE3  = 'FREQ'               / Frequency (linear)
> CRVAL1  =       273.6641595834 / [deg] Coordinate value at reference point
> CRVAL2  =      -17.86695000001 / [deg] Coordinate value at reference point
> CRVAL3  =       233562367862.0 / [Hz] Coordinate value at reference point
> PV2_1   =                  0.0 / SIN projection parameter
> PV2_2   =                  0.0 / SIN projection parameter
> LONPOLE =                180.0 / [deg] Native longitude of celestial pole
> LATPOLE =      -17.86695000001 / [deg] Native latitude of celestial pole
> RESTFRQ =       234500000000.0 / [Hz] Line rest frequency
> MJDREF  =                  0.0 / [d] MJD of fiducial time
> DATE-OBS= '2017-09-11T01:47:10.440000' / ISO-8601 time of observation
> MJD-OBS =      58007.074426389 / [d] MJD of observation
> OBSGEO-X=       2225142.180269 / [m] observatory X-coordinate
> OBSGEO-Y=      -5440307.370349 / [m] observatory Y-coordinate
> OBSGEO-Z=      -2481029.851874 / [m] observatory Z-coordinate
> RADESYS = 'ICRS'               / Equatorial coordinate system
> SPECSYS = 'LSRK'               / Reference frame of spectral coordinates
> HISTORY CASA START LOGTABLE
> ...snip...
> HISTORY CASA END LOGTABLE
> HISTORY Written by spectral_cube v0.5.1.dev194+g3ec43af on 2021/09/29-08:46:43
> END
> ```
> 
> (the problem exists with the original CASA version too)

Out of curiosity, CASA lets you make an 513x513 image? I thought tclean only accepts multiple of 2 3 5 7

**Comment by keflavich** [comment]
you can make files any size, but yeah, 513 is not an optimal one...

**Comment by keflavich** [comment]
Will future versions of CARTA be able to load odd-sized images?

**Comment by kswang1029** [comment]
> Will future versions of CARTA be able to load odd-sized images?

Yes the current dev should support those
