### ISSUE TITLE
Specify token on command line?

### ISSUE THREAD

**Issue by keflavich** [CARTAvis/carta#97]
I frequently have to restart CARTA, and when I do, it generates a new token each time - which is inconvenient when reloading in the browser.  Is there any way to specify the token when starting up CARTA to make reloading more convenient?

**Comment by kswang1029** [comment]
CARTA_AUTH_TOKEN=0000 carta

should work. (Replace 0000 to some other custom string)

**Comment by keflavich** [comment]
Awesome, thanks!  If this isn't in the docs (I didn't see it, but I may not have looked hard enough), it would be super helpful to add there.
